### ISSUE TITLE
Show directory average file size

### ISSUE THREAD

**Issue by brunoais** [shundhammer/qdirstat#104]
Is it possible to have a column that displays the average file size (and drilling down on directories)?
In my case, it helps cleaning based on what is the most efficient per file for directories.

**Background:**
In the bottom graphic, I can find the biggest files color coded most easily. So, if I want to go after the biggest files, I can just go to the graph and click the biggest color squares.
In my case, I have squares of many different sizes but similar sizes and they are about similar content (think like photo album for a baseline).
If I want to delete or (lossly) compess, usually I will want to delete or compress the whole set.
The sets have different sizes. Can be 15 images, 100 images, 70 images.....

**Possible solution**
I believe that selecting when to do those mass deletes in an efficient way would require knowing the average file size in a set instead of the actual size of the directory.

Could such feature be added to qdirstat?

Here's an example of what I see. Lost of small files with some that are a bit bigger but still not knowing if they are worth to compress.....
![disc_data_organized](https://user-images.githubusercontent.com/639467/57844537-26d26d00-77c8-11e9-9610-6a43d8a84e54.png)

**Comment by shundhammer** [comment]
Did you try the file size statistics? It might be a lot more useful for you.
You can call that for the complete tree or only for a subdirectory.

https://github.com/shundhammer/qdirstat/blob/master/doc/stats/File-Size-Histogram.md

I think it's even more useful since you get the median, not the average. The median is typically a much better measure as explained here:

https://github.com/shundhammer/qdirstat/blob/master/doc/stats/Median-Percentiles.md

**Comment by shundhammer** [comment]
Please notice that you can also combine this with the file _type_ statistics:

![QDirStat-histogram-jpg-work](https://user-images.githubusercontent.com/11538225/57845319-0effe680-77d2-11e9-95b3-790685f1da50.png)

**Comment by brunoais** [comment]
I've been tinkering with file statistics. It gives a really good high level view on what kinds of file sizes I'm dealing with. I find it quite useful to know...
"How big, on average, are my files?" "How big are my png images?" "What is the usual size for jpeg in this directory? And how much is outliers?"
That does help me quite much but.... It doesn't help me knowing:
"For this directory, large are the files?" applied to many directories one after the other. I can run the file size statistics on each directory one by one but that doesn't help.
For example:
 (one of the more extreme cases)  One directory is ~650MB big but it has ~2000 images. That's an average of ~300KB per image. That's fine. Probably already well compressed.
Another extreme one: The directory is ~470MB but it only has ~200 images. That's an average of 2.3MB per image. Probably there would be room available for compression.

Does it make more sense if I explain that way @shundhammer ?

**Comment by shundhammer** [comment]
If you have a really flat hierarchy, that might work. But as you cascade values up the tree, any irregular averages will pretty much even out, so it won't be very useful there. Also, what you need would be restricted only to one file type; you want the average of your .jpg or your RAW files, preferably each type separately. I you have different things in any such directory, this may already have considerable impact: A high average in one directory will be diluted pretty quickly on the next level up the tree.

So what you really need is a dedicated tool for this purpose. And while we are at it, it might even tell you a compression level based on the image's megapixels; as you are using newer and better cameras, the megapixel count will inevitably increase, and that average per directory will become a lot less useful.

**Comment by brunoais** [comment]
I see. Thanks for the insight.
It appears that my use-case is really niche. I will use your suggestions to try crafting a bash script for myself. Thank you for the fast responses.
