### ISSUE TITLE
Regression: qdirstat-cache-writer to stdout

### ISSUE THREAD

**Issue by phiresky** [shundhammer/qdirstat#105]
Trying to run qdirstat-cache-writer with a pipe worked previously but now doesn't, probably since https://github.com/shundhammer/qdirstat/commit/49860e63560834cd8aac3e5ad5271413d83e3966.

Example:

`qdirstat-cache-writer /usr/lib - | qdirstat -c /dev/stdin` worked previously, now it doesn't.

**Comment by shundhammer** [comment]
Oops; thank you, that is a bad regression indeed.

Reverted those changes for the time being:

- 49860e63560834cd8aac3e5ad5271413d83e3966
- 2d40a0dd8d7a065f8a500c5f541e473249a2fbe7

If anybody feels like bringing them back without breaking common use cases like using good old-fashioned Unix/Linux shell pipelines, that's okay with me. But until then, I very much prefer to stick with the simpler version that does _not_ introduce regressions.

**Comment by phiresky** [comment]
I've kinda fixed it here: https://gist.github.com/phiresky/7b7559623317640e17fd783c7b09ab39#file-qdirstat-cache-writer-L159-L166 but that version also includes the change to remove the dependency from uri_escape.

**Comment by shundhammer** [comment]
Also, if a system is really critically short of disk space so the two-step process that the script does internally becomes a problem, it is easy to do it manually in one step with this simple pipeline:

```shell
qdirstat-cache-writer /targetdir - | gzip >targetdir.cache.gz
```

**Comment by phiresky** [comment]
might want to mention @bcarnes since they wrote that code
