### ISSUE TITLE
Suggestion: Folders with many items in them that get collapsed in the Treemap could be colored according to the dominant filetype inside

### ISSUE THREAD

**Issue by Hubcapp** [shundhammer/qdirstat#108]
Here's a small section of the treemap for my hard drives:

<img src="https://i.imgur.com/GFZt9Rn.png"/>

I maintain the default "bright teal" color for images, but because the images are very small in filesize, qdirstat gives it the "folder with lots of files in it" color, which is gray.

If qdirstat were programmed to recognize ">95% of the data in this directory can be categorized as image files, I should paint the tile for the color of the Image mimetype", that would improve users' recognition of what is inside the folders.

**Comment by shundhammer** [comment]
Yes, that idea has come up in another issue some time ago. This would be an improvement in many cases.

**Comment by shundhammer** [comment]
Experiments so far showed that the colors look very much differently when rendered with the directory gradient technique, and it looks confusing when rendered like a file as a cushion.

So, as much as I'd like to have this, this is a lot harder than it sounds.

Closing for now.
