### ISSUE TITLE
Multiselect "Ctrl+C" only copies last selection

### ISSUE THREAD

**Issue by stdedos** [shundhammer/qdirstat#112]
I am trying to copy/paste the selected items' path (folders).

However, `Ctrl+C` only takes the last selected item's path.

Version `1.5.91-git` (you might also want to change that to `git-describe` i.e. `1.5.91-2-gd4cef3f`, and also make your version tags annotated, to be used cleanly with `git-describe`)

**Comment by shundhammer** [comment]
This is the intended behaviour. This uses the _current_ item (which is always a single one), not the set of _selected_ items.
