### ISSUE TITLE
Feature Request: Fool-proof Cut-off in the Histograms

### ISSUE THREAD

**Issue by shundhammer** [shundhammer/qdirstat#117]
_Received via mail from **Nicolas Brisset**:_

While I'm writing you a mail, I'd like to add another proposal. I fell into the trap a couple of times, and I guess I'm not the only one: when using histograms, the automatic cut-off is computed only on file counts (I guess). I had some directories with few but huge files (typicall core dumps or archive files) and when I checked the histogram I first could not see them. I would suggest adding a warning overlaid on the histogram, or maybe an option in the settings to compute the cut-off based on file counts (as now) but to check whether the sum of files shown in the histogram accounts for the right percentage (99%?) of the total size.

**Comment by shundhammer** [comment]
It's already there, and really prominent, too:

![QDirStat-histogram](https://user-images.githubusercontent.com/11538225/62135930-6860b780-b2e3-11e9-919f-1fc11bee4c3c.png)

Why and how that cut-off is generated is documented extensively here:

https://github.com/shundhammer/qdirstat/blob/master/doc/stats/File-Size-Histogram.md

> QDirStat by default uses some heuristics to determine useful boundaries for the histogram: It uses the interquartile distance (Q3 - Q1) and adds some generous distance to the left and to the right of Q1 and Q3:
>
> leftBoundary  = Q1 - 3 * (Q3 - Q1)
>
> rightBoundary = Q3 + 3 * (Q3 - Q1)

https://github.com/shundhammer/qdirstat/blob/master/doc/stats/Overflow-Area.md

**Comment by brisset** [comment]
Thanks for the explanations. In fact, I had failed to understand the cut-off view at first glance. May I suggest to add a short explanation on the cut-off view? Maybe something like a subtitle explaining "Some files are currently not displayed in the histogram, they amount for x % of the file count and y % of disk space. You can click on the "Options" button below to change histogram settings". You can also make it a tooltip if such a text is too invasive.
Maybe a legend would also help? (red = masked files).

To better explain why I had a problem with that view, find below a screenshot of the directory I was using it with. This is under a mate desktop with a dark theme... Not very easy to read!
![Screenshot-File Size Statistics](https://user-images.githubusercontent.com/5457181/62191313-91c92400-b373-11e9-9bc4-6091dcb873a7.png)

**Comment by shundhammer** [comment]
Now explicitly using a white background and black text color for the complete histogram view, even for dark widget themes:

![QDirStat-histogram-dark-widget-theme](https://user-images.githubusercontent.com/11538225/62412239-b0dbe600-b5ff-11e9-914b-1506d6b1be03.png)

**Comment by shundhammer** [comment]
The very concept of that QGraphicsView / QGraphicsScene / QGraphicsTextItem using the application's widget theme palette is broken by design: Those classes are designed to be used as a canvas to draw custom graphics.

**Of course** such custom graphics use custom colors which are not dependent at all on the current widget theme. That default behaviour is completely insane and useless.
