### ISSUE TITLE
Feature requests for exclude rules

### ISSUE THREAD

**Issue by tarchive** [shundhammer/qdirstat#120]
Hi, I have a few suggestions for additional features to your already excellent program.

1. Excluded rules are currently case sensitive - Can you add an option in the rule to toggle sensitive/insensitive?
   Ex. *.mov does not exclude file movie.MOV

2. Include list - Similar to excused except only the specified rules are allowed. It would save a lot of effort when only trying to analyze a specific file type.

3.  Exclude list rules to support MIME categories - Right now if i want to exclude images i must specify every type individually. Since there is already a MIME category list in the configuration, it would be nice to just to call the category "Images" and have all types excluded.

4.  Save/load profiles - Currently this would be helpful but with the above implemented maybe it would not be needed as much. For example if i only want to analyze PDFs, i have to set a lot of exclude filters. Once they are set it works great, but now if i want to analyze compressed documents, i have to reset a lot of filters. Being able to save and reload these filters would save me a lot of time when i need to switch back and forth.

Looking forward to your thoughts.

**Comment by shundhammer** [comment]
Quick answers first...

> 1. Excluded rules are currently case sensitive - Can you add an option in the rule to toggle sensitive/insensitive?

That should be easy enough. Okay.

> 4. Save/load profiles - Currently this would be helpful but with the above implemented maybe it would not be needed as much. For example if i only want to analyze PDFs, i have to set a lot of exclude filters. 

That does not sound that useful as a general tool for everybody. But what you can do right now already: Start QDirStat from a script that moves away the existing exclude rules and replaces them with another set, and when QDirStat exits move it back. Something like

```bash
#!/bin/sh
# 

# Directories and files
my_config_dir=$HOME/QDirStat-custom-configs
custom_config=$my_config
config_dir=$HOME/.config/QDirStat
exclude_config=$config_dir/QDirStat-exclude.conf
saved_config=${exclude_config}.old

# Save old configuration
mv $exclude_config $saved_config

# Copy custom configuration here
cp $custom_config $exclude_config

# Start QDirStat (with parameters given to this shell script)
qdirstat !*

# Optional: Copy potentially changed config back to custom config dir
cp $exclude_config $custom_config

# Restore old exclude config
mv $saved_config $exclude_config
```

(untested, but you get the idea)

**Comment by shundhammer** [comment]
Also, just to clarify: You cannot exclude files of a given file type. 

![QDirStat-config-exclude](https://user-images.githubusercontent.com/11538225/73272534-d0388200-41e2-11ea-9180-25bc7b1ba910.png)

"Match against... ...any file in that directory" with "*.pdf" means that it will exclude any directory _completely_ that has at least one "*.pdf" file in it. It does **not** mean that it will exclude only PDF files in those directories.

Is that really what you want?

Doing it like that was an intentional design decision for performance.

**Comment by shundhammer** [comment]
So, my guess is that you were confused what this exclude feature actually does; it does not exclude individual files. It always affects the complete directory that the file is in. If that is the case, the extension of the feature to what you suggested pretty much lose their usefulness.

**Comment by tarchive** [comment]
Yep, your right, I misunderstood that functionality of exclude. I will need to reevaluate my results before i add anything additional here but likely this ticket can stay closed. 

I will definitely take a crack at scripting the save/load config. Thanks for the input and suggestions.
