### ISSUE TITLE
(feature request) qdirstat appimage

### ISSUE THREAD

**Issue by ghcatt** [shundhammer/qdirstat#123]
greetings,

any chance for a linux appimage build in the future?

have a look over here for more details: https://github.com/AppImage/AppImageKit/wiki

**Comment by shundhammer** [comment]
You mean... shrink-wrapping an application that is meant to combat wasting disk space into a bundle containing all shared libs etc. to make the result extra large? :smiley: 

No.

Appimage, flatpaks, snap packages, dockers etc. are the bane of our time. It perverts the idea of having shared libs. If that is a good thing, why not simply use static linking? That way, at least you don't need yet another runtime environment to run yet another blown-up package format.

**Comment by ghcatt** [comment]
so the point you criticize is merely targeted on disk space usage? seems a bit off in times where games come by in giant gb size attacks.

despite the other formats you mention (which in fact need extra software to be installed and or daemon processes running, afaik), i very much like this format for its user-friendly, compact & truly portable aspect. no more need to reinstall software on a clean install, or to be forced to download huge updates when on a rolling-release only because of some heavy tools you rarely make use of.

the alternative (aur) seems much more like the real bane to me for various reasons, but that is another story... not to speak of the lame compile-processes over and over again in general.

in this case i very much prefer a ready to go single-file binary, even if it may be at the cost of a (sometimes) increased disk-space usage. 

anyway, that is just my humble point of view.

all the best

**Comment by shundhammer** [comment]
When you build QDirStat, you will end up with a single binary file. All auxiliary files (icons etc.) are compiled into the sources. The .desktop file is optional and really only useful to start it from the menu of a desktop environment.

The QDirStat binary is of course dynamically linked, so you need the required shared libs on your system; but that's only the Qt libs and libz. It does not have a gazillion of dependencies.

**Comment by shundhammer** [comment]
If disk size is abundant in your environment, then why bother with a disk space analyzer program like QDirStat in the first place? This sounds like a self-defeating argument. :smiley: 

Another issue is additional packaging work for yet another package format. Starting with AppImage, where would that end? Wouldn't those who like FlatPack, Snap and Docker images want their favourite format supported with the exact same justification?

I am the upstream author; I provide a source repository and, for official releases, source tarballs.

I also do the packaging for SUSE Linux (Tumbleweed, Leap, SUSE Linux Enterprise) because I work at that company. But that's it.

For any other kind of packaging and/or distro, if there is a packager who volunteers to do it, they can do it, but it is their responsibility to take care of packaging bugs (which more often than not are the result of an ever-changing target environment where dependencies change, new packaging policies are introduced, files are moved around in the filesystem and whatever).

**Comment by ghcatt** [comment]
> If disk space is abundant in your environment, then why bother with a disk space analyzer program like QDirStat in the first place? This sounds like a self-defeating argument. smiley

who says it's use case is for this reason alone :)

also, it was not addressed at qdirstat solely, but tools in general.

so the 'workaround' is to build from source, come to receive a single file -- in this particular case -- which still asks for a few deps to get it running? seems not very practical, not to think of heavyweight programs demanding far more dependencies until ready to start.

i see your point regarding the extra packaging, perhaps a compromise could have been found in releasing only major version as an appimage? far better than nothing at all. also, i understand appimages more in the direction of portableapps, offering users the possibility to test software in a quick and easy manner, so it is not really to be merged with other formats aiming to replace traditional linux package-management concepts in total.

like or disklike the concept. in the end, it was just a harmless suggestion, after all.

**Comment by shundhammer** [comment]
> so the 'workaround' is to build from source, come to receive a single file -- in this particular case -- which still asks for a few deps to get it running? seems not very practical

The whole point of Open Source is to provide the source code so users can see what the software does and decide whether or not they want to trust it, or change it if they don't like it.

For those who don't want to do that, there are binary packages. In that case, you put your faith and trust in the packagers and distributors.

Don't forget that they also provide security updates for the dependencies. If your distribution gets an important security update for a library package, anything that comes with the same library package bundled will simply not get the update, leaving the security problems that the update fixed open.

This alone is plenty reason not to do that.

Do you think packagers for such bundled package systems like AppImage redistribute their AppImage every time an update for any of all the library packages that they also ship is released? Do you think that they are even aware that there is such an update? And even if they do: What additional delay is involved until the updates make it to the end user?

I have been in contact with many package formats. Scripting languages typically invent their own; CPAN for Perl, Gem for Ruby, others for Python and Java. Every single one of them reinvents the wheel time and again. And every single one of them comes across the exact same problems that the other package formats also had to overcome, and they all tend to make the same mistakes and introduce the same bugs until it has exactly the same complexity and quirks than the older package system that they wanted to overcome. They all start simple, and by the time the problems are solved, there is no more simpicity.

I have no reason to believe that AppImage, FlatPack, Snap or whatever are any different in that regard. They may try to avoid one class of problem (dependencies), but they introduce a whole different class (security updates).

> not to think of heavyweight programs demanding far more dependencies until ready to start.

This is getting a very generic philosophical discussion. This is about QDirStat, not any other software.

**Comment by ghcatt** [comment]
you raised some points of truth here that can not be denied. if there is major security warnings concerning a specific tool, it should of course be updated. there is no doubt about it and everybody should do so accordingly. wether all dependencies are updated remains to the packager which ideally is the developer himself.

on the other hand, nothing is perfect and i never stated so. of course there is some flaws in every eco-system, but that does not mean to not embrace new ideas and stay open minded towards change, dont you think?

i take it for what it is and it fits my needs, that is all i can say about it. at least, i can say i prefer to choose appimages over aur packages for sure... but that again is just my point of view.

i can understand your distant attitude towards appimages, maybe you also see the good aspects in it and why i would like to see it being supported?

**Comment by shundhammer** [comment]
See also #168.

**Comment by medavox** [comment]
> You mean... shrink-wrapping an application that is meant to combat wasting disk space into a bundle containing all shared libs etc. to make the result extra large? 😃

> No.

> A lot of things that used to be user configurable in KDE 3 are not configurable anymore, and when you approach the KDE 4/5 developers about that, they will tell you that this is intentional, and they do not intend to bring those config options back. Well, thanks a lot; this is the Apple approach where they think they know what is good for you, and you are just too stupid.

All the above are your own words :)

Rather than deciding for us whether what you think is our usecase is valid, maybe just appraise the feature request based on technical feasibility effort required etc.

**Comment by shundhammer** [comment]
I am not going to keep repeating myself endlessly.
