### ISSUE TITLE
Sent cores over e-mail

### ISSUE THREAD

**Issue by stdedos** [shundhammer/qdirstat#125]
Hello there,

I've sent you a core in your gmx e-mail (since it's ~100MB). Have you checked?

**Comment by shundhammer** [comment]
No, there is nothing. Not sure if it got stuck by GMX limits or by one of my own spam filters.

But in general, cores are only useful for generating a backtrace anyway, in particular with the level of complexity that comes with a Qt / C++ program.

So if you get a core dump, please use `gdb` to generate the backtrace and paste the backtrace to the issue tracker (formatted as code with a separate line with three backticks before and after it).

Please also add a description what you did and the corresponding QDirStat log file `/tmp/qdirstat-$USER/qdirstat.log` (also formatted as code).

It's also good to have all information in the issue tracker and not floating around as personal messages so it is recorded and documented for other users and also for other developers working on it.
