### ISSUE TITLE
Make columns resizeable

### ISSUE THREAD

**Issue by marisn** [shundhammer/qdirstat#127]
At the moment it is not possible to resize widths of columns. It is not an issue unless one has directories/files with really loooooooong names.
I have a few files with names going over 200 chars (title of document as file name for fast search). Thus displaying it makes „Name“ column become too wide to be useable.

Thus it should be possible to make at least „Name“ column narrower (just display an ellipsis at the end of shortened names).

**Comment by shundhammer** [comment]
> At the moment it is not possible to resize widths of columns.

Yes, it is. And it's even **extensively** documented, even with a screenshot.

https://github.com/shundhammer/qdirstat#features

> You can configure what columns to display in the tree view and in which order. The only thing that is fixed is the "Name" column which is always there and always the first (leftmost). Use the context menu in the tree header to unlock column widths. Drag columns to the left or right to change their order.

https://github.com/shundhammer/qdirstat#more-screenshots

![QDirStat-column-config](https://user-images.githubusercontent.com/11538225/78377982-a039a080-75d0-11ea-85cb-df01b84f3afe.png)
