### ISSUE TITLE
build error on OS X (10.9)

### ISSUE THREAD

**Issue by anovstrup** [shundhammer/qdirstat#13]
I ran `qmake` and then `make` on OS X, and it seemed to be going fine until it got to Logger.cpp. Here's the output:

> clang++ -c -pipe -stdlib=libc++ -mmacosx-version-min=10.7 -g -arch x86_64 -Wall -W -DQ_DECL_OVERRIDE="" -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/local/Cellar/qt/4.8.6/mkspecs/unsupported/macx-clang-libc++ -I. -I/usr/local/Cellar/qt/4.8.6/lib/QtCore.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.6/lib/QtCore.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.6/lib/QtGui.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.6/lib/QtGui.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.6/include -I.moc -I. -F/usr/local/Cellar/qt/4.8.6/lib -o .obj/Logger.o Logger.cpp
Logger.cpp:260:2: error: use of undeclared identifier 'abort'
        abort();
        ^
1 error generated.
make[1]: *** [.obj/Logger.o] Error 1
make: *** [sub-src-make_default-ordered] Error 2

**Comment by shundhammer** [comment]
Please try again with https://github.com/shundhammer/qdirstat/commit/669e46802560f08c755d8afcf544494f590046c5

This adds the missing include. Looks like on gcc platforms, this stdlib.h is indirectly included by some other include file, so it didn't complain about it.

Please reopen if the problem persists even with this patch.
