### ISSUE TITLE
Unable to compile under macOS

### ISSUE THREAD

**Issue by teras** [shundhammer/qdirstat#131]
Hello!
I was trying to compile qdirstat under latest macos Catalina, but it fails.
Here are the last output, any help will be appreciated.

/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -c -pipe -stdlib=libc++ -g -std=gnu++11  -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.13 -Wall -Wextra -fPIC -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -I/usr/local/Cellar/qt/5.14.2/lib/QtWidgets.framework/Headers -I/usr/local/Cellar/qt/5.14.2/lib/QtGui.framework/Headers -I/usr/local/Cellar/qt/5.14.2/lib/QtCore.framework/Headers -I.moc -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I/usr/local/Cellar/qt/5.14.2/mkspecs/macx-clang -F/usr/local/Cellar/qt/5.14.2/lib -o .obj/moc_UnreadableDirsWindow.o .moc/moc_UnreadableDirsWindow.cpp
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -stdlib=libc++ -headerpad_max_install_names  -arch x86_64 -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.13 -Wl,-rpath,@executable_path/../Frameworks -o qdirstat.app/Contents/MacOS/qdirstat .obj/main.o .obj/ActionManager.o .obj/AdaptiveTimer.o .obj/Attic.o .obj/BreadcrumbNavigator.o .obj/BucketsTableModel.o .obj/BusyPopup.o .obj/Cleanup.o .obj/CleanupCollection.o .obj/CleanupConfigPage.o .obj/ConfigDialog.o .obj/DataColumns.o .obj/DebugHelpers.o .obj/DelayedRebuilder.o .obj/DirInfo.o .obj/DirReadJob.o .obj/DirSaver.o .obj/DirTree.o .obj/DirTreeCache.o .obj/DirTreeModel.o .obj/DirTreePatternFilter.o .obj/DirTreePkgFilter.o .obj/DirTreeView.o .obj/DotEntry.o .obj/DpkgPkgManager.o .obj/Exception.o .obj/ExcludeRules.o .obj/ExcludeRulesConfigPage.o .obj/ExistingDirCompleter.o .obj/ExistingDirValidator.o .obj/FileDetailsView.o .obj/FileInfo.o .obj/FileInfoIterator.o .obj/FileInfoSet.o .obj/FileInfoSorter.o .obj/FileSizeLabel.o .obj/FileSizeStats.o .obj/FileSizeStatsWindow.o .obj/FileTypeStats.o .obj/FileTypeStatsWindow.o .obj/GeneralConfigPage.o .obj/HeaderTweaker.o .obj/HistogramDraw.o .obj/HistogramItems.o .obj/HistogramOverflowPanel.o .obj/HistogramView.o .obj/ListEditor.o .obj/LocateFilesWindow.o .obj/Logger.o .obj/MainWindow.o .obj/MessagePanel.o .obj/MimeCategorizer.o .obj/MimeCategory.o .obj/MimeCategoryConfigPage.o .obj/MountPoints.o .obj/OpenPkgDialog.o .obj/OutputWindow.o .obj/PacManPkgManager.o .obj/PanelMessage.o .obj/PercentBar.o .obj/PercentileStats.o .obj/PkgFileListCache.o .obj/PkgFilter.o .obj/PkgInfo.o .obj/PkgManager.o .obj/PkgQuery.o .obj/PkgReader.o .obj/Process.o .obj/ProcessStarter.o .obj/Refresher.o .obj/RpmPkgManager.o .obj/SelectionModel.o .obj/Settings.o .obj/SettingsHelpers.o .obj/ShowUnpkgFilesDialog.o .obj/StdCleanup.o .obj/Subtree.o .obj/SysUtil.o .obj/SystemFileChecker.o .obj/Trash.o .obj/TreemapTile.o .obj/TreemapView.o .obj/UnpkgSettings.o .obj/UnreadableDirsWindow.o .obj/qrc_icons.o .obj/moc_AdaptiveTimer.o .obj/moc_BreadcrumbNavigator.o .obj/moc_BucketsTableModel.o .obj/moc_BusyPopup.o .obj/moc_Cleanup.o .obj/moc_CleanupCollection.o .obj/moc_CleanupConfigPage.o .obj/moc_ConfigDialog.o .obj/moc_DataColumns.o .obj/moc_DelayedRebuilder.o .obj/moc_DirReadJob.o .obj/moc_DirTree.o .obj/moc_DirTreeCache.o .obj/moc_DirTreeModel.o .obj/moc_DirTreeView.o .obj/moc_ExcludeRules.o .obj/moc_ExcludeRulesConfigPage.o .obj/moc_ExistingDirCompleter.o .obj/moc_ExistingDirValidator.o .obj/moc_FileDetailsView.o .obj/moc_FileSizeLabel.o .obj/moc_FileSizeStatsWindow.o .obj/moc_FileTypeStats.o .obj/moc_FileTypeStatsWindow.o .obj/moc_GeneralConfigPage.o .obj/moc_HeaderTweaker.o .obj/moc_HistogramView.o .obj/moc_ListEditor.o .obj/moc_LocateFilesWindow.o .obj/moc_MainWindow.o .obj/moc_MessagePanel.o .obj/moc_MimeCategorizer.o .obj/moc_MimeCategoryConfigPage.o .obj/moc_OpenPkgDialog.o .obj/moc_OutputWindow.o .obj/moc_PanelMessage.o .obj/moc_PercentBar.o .obj/moc_PkgReader.o .obj/moc_Process.o .obj/moc_ProcessStarter.o .obj/moc_Refresher.o .obj/moc_SelectionModel.o .obj/moc_Settings.o .obj/moc_ShowUnpkgFilesDialog.o .obj/moc_TreemapView.o .obj/moc_UnreadableDirsWindow.o   -F/usr/local/Cellar/qt/5.14.2/lib -lz -framework QtWidgets -framework QtGui -framework AppKit -framework Metal -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL   
cd scripts/ && ( test -e Makefile || /usr/local/Cellar/qt/5.14.2/bin/qmake -o Makefile /Users/teras/Sources/qdirstat/scripts/scripts.pro ) && /Applications/Xcode.app/Contents/Developer/usr/bin/make -f Makefile 
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -stdlib=libc++ -headerpad_max_install_names  -arch x86_64 -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.13 -Wl,-rpath,@executable_path/../Frameworks -o .app/Contents/MacOS/    -F/usr/local/Cellar/qt/5.14.2/lib -framework QtGui -framework AppKit -framework Metal -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL   
Undefined symbols for architecture x86_64:
  "_main", referenced from:
     implicit entry/start for main executable
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [.app/Contents/MacOS] Error 1
make: *** [sub-scripts-make_first-ordered] Error 2

**Comment by shundhammer** [comment]
I don't know; I don't use MacOS X.

This has been reported before (e.g. issue #65, issue #14), and as far as I can tell, it's a problem of not having a Qt build environment correctly set up. Please make sure you can compile and link a "hello, world" type program in Qt. The Qt documentation will contain instructions how to do that on MacOS X.

**Comment by teras** [comment]
Hello
I don't think it's a macOS problem, since I successfully compile a lot of qt apps up to now.

If you look at the last command

**/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -stdlib=libc++ -headerpad_max_install_names -arch x86_64 -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.13 -Wl,-rpath,@executable_path/../Frameworks -o .app/Contents/MacOS/ -F/usr/local/Cellar/qt/5.14.2/lib -framework QtGui -framework AppKit -framework Metal -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL**

it seems that something is missing.

If you clear out the paths which don't play any role, we get this command instead:

**clang++ -stdlib=libc++ -headerpad_max_install_names -arch x86_64 -Wl,-syslibroot,MacOSX10.15.sdk -mmacosx-version-min=10.13 -Wl,-rpath,@executable_path/../Frameworks -o .app/Contents/MacOS/ -F/usr/local/Cellar/qt/5.14.2/lib -framework QtGui -framework AppKit -framework Metal -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL**


There's a `-o` parameter but points to a folder and there are no input files. Maybe this is the problem?

**Comment by teras** [comment]
Also see https://github.com/shundhammer/qdirstat/pull/132
