### ISSUE TITLE
"continue reading at mount point" closes the opened tree

### ISSUE THREAD

**Issue by HieronymusCH** [shundhammer/qdirstat#135]
Hi there

if I right click on another media to "continue reading at mount point" it closes the tree to the base level and I have to crawl through the whole tree again.

**Comment by shundhammer** [comment]
You are right. Let me check what I can do here.

**Comment by shundhammer** [comment]
That was a surprisingly tricky one with all the signals being sent and received, some of them based on single-shot timers. But now it should be fixed.

If you can, please check out and build Git master and test.
