### ISSUE TITLE
Selecting multiple files and right click copy URL should copy URLs of all selected files

### ISSUE THREAD

**Issue by CodingSpiderFox** [shundhammer/qdirstat#138]
It seems that it currently only copies the path of the file that was selected last when selecting multiple files with CTRL+Mouseclick

**Comment by shundhammer** [comment]
Of course; this is intentional. What would anybody do with a large list of files with their full paths?

**Comment by shundhammer** [comment]
This is a duplicate of issue #112.

**Comment by CodingSpiderFox** [comment]
-See what are the biggest files
-Order list by name
-Provide a summary of those that start with the same substring.
I needed this to file this issue:

https://github.com/jshiell/checkstyle-idea/issues/494

**Comment by shundhammer** [comment]
So what you _really_ needed was to start a terminal window in that directory (Ctrl-T) and then use a simple `ls` command that sorts by size and then use the first 10 (or however many) items of that list:

```
ls -lhS | head -n 10
```

This has the added benefit of also showing the size of each file, and not repeating the redundant path for each one.

QDirStat is not meant as a substitute for simple shell commands; it is meant to complement them.

**Comment by CodingSpiderFox** [comment]
Thxs
