### ISSUE TITLE
Documentation: build instructions for SUSE need correction

### ISSUE THREAD

**Issue by Kadilov** [shundhammer/qdirstat#140]
In openSUSE Leap 15.2, after installing packages suggested by readme file `qmake` is missing.
`cnf qmake` output:
```
The program 'qmake' can be found in the following package:
  * libqt4-devel [ path: /usr/bin/qmake, repository: zypp (repo-oss) ]

Try installing with:
    sudo zypper install libqt4-devel
```

**Comment by shundhammer** [comment]
`libqt4-devel` is the wrong package: This would be for building against Qt4, not Qt5. While that _should_ still work, Qt4 is not the recommended and default build environment; it's Qt5. And `qmake` for Qt5 is included (via dependencies) when you install `libQt5Widgets-devel`.

**Comment by Kadilov** [comment]
Ok, `libQt5Widgets-devel ` was installed, I needed `export PATH=/usr/lib64/qt5/bin:$PATH` to run `qmake`.

**Comment by Kadilov** [comment]
@shundhammer Maybe it was obvious, but afterwards I realised that there is no Qt5 binary with the name `qmake` in openSUSE, only a symlink that points to `/usr/bin/qmake-qt5`. This is why the command did not work by default and I bothered you. I think rewriting this step as unconditional will make no harm, something like:
"Make sure that the Qt5 version of 'qmake' is in your $PATH and Qt4 version does not take precedence:"
Currently:
"If you also have a Qt4 development environment installed, make sure that the Qt5 version of 'qmake' is the first in your $PATH:"

**Comment by shundhammer** [comment]
That might be a matter of `update-alternatives`.
