### ISSUE TITLE
Forum for MacOS devs/hackers

### ISSUE THREAD

**Issue by gregfenton** [shundhammer/qdirstat#141]
Thoughts on where MacOS devs/hackers might chat about efforts working on qdirstat?  Maybe a page in the wiki or something?  Or do y'all have a super-secret discord server hiding in the darkwebz??  😄 

I just tried building qdirstat for the very first time this morning.  Compiled decently (a few warnings), and it is up and scanning my drive now (albeit with a ton of "allow access?" dialogs as it is running).  Yay!!!

Can't guarantee I could devote much time to the effort, but getting coordinated across folks' efforts would be a first step.

**Comment by shundhammer** [comment]
Pick your forum of choice and happily chat away with like-minded interested hackers... :smiley: 

But if you want me involved, this issue tracker is a good place.

If anybody wants to do a real MacOS X port, please go ahead. I myself have zero MacOS X know-how; all I know is that there is some BSD under the hood. How far that goes and at what point MacOS X (the Apple part) takes over, I have no clue.

I suspect that differences start appearing at places like the trash bin handling and cleanup operations in general. Most likely there won't be any support for package manager operations (but this is just a guess; I don't really know), so finding out what software package a file belongs to or the packages or unpackaged files view might not be supported on that platform.

There are probably also issues with MacOS X GUI handling; but then, Qt might already handle most of that. QDirStat uses Qt classes wherever possible and reasonable, and Qt should abstract that well enough.

Other than that, it's POSIX function calls and sometimes calling some external programs (cleanups, package manager operations), and AFAICS that should all work well enough on MacOS X.

Packaging QDirStat might also be another aspect, also handling installation directories and auxiliary files (the icon and the .desktop file).

When you start, please make sure to read the doc/Contributing.md document and also the doc/GitHub-Workflow.md document:

- https://github.com/shundhammer/qdirstat/blob/master/doc/Contributing.md
- https://github.com/shundhammer/qdirstat/blob/master/doc/GitHub-Workflow.md

I also want to avoid tons of `#ifdef`s in the code (visual clutter, untested / uncompiled code paths). If anything is very specific to MacOS X, it should be factored out to separate source files and some conditional compilation in the QMake .pro files. But I am getting ahead of things here. :smiley:

**Comment by shundhammer** [comment]
Created a Wiki page for this and linked it from the Wiki start page:

https://github.com/shundhammer/qdirstat/wiki/QDirStat-MacOS-Dev
