### ISSUE TITLE
CoW support

### ISSUE THREAD

**Issue by kev009** [shundhammer/qdirstat#142]
Can you generalize the btrfs space features to all CoW filesystems, for instance ZFS (on Linux and BSD)?

**Comment by shundhammer** [comment]
The only thing that QDirStat does with that is to warn the user in the new "Mounted Filesystems" window about Btrfs misbehaving in weird ways when a Btrfs partition is detected:


![btrfs-warning](https://user-images.githubusercontent.com/11538225/88671343-7ad42380-d0e6-11ea-9017-009130f0937a.png)


That warning points to the  [new document about Btrfs](https://github.com/shundhammer/qdirstat/blob/master/doc/Btrfs-Free-Size.md).

This is just self-defence against the inevitable questions that users have when all the different tools report different inconsistent values (and consequently bug reports).

I don't have or use ZFS; I have zero experience with it. Maybe it misbehaves in similar ways, maybe it doesn't. I don't know. I am certainly not in a position to write (or even maintain) a similar document for ZFS.
