### ISSUE TITLE
Non-issue

### ISSUE THREAD

**Issue by shundhammer** [shundhammer/qdirstat#144]
This is dedicated to all those spammers who keep poisoning Google search results with snippets of articles from Open Source projects such as QDirStat; they are making Google searches a royal PITA. 
May they rot in hell forevermore. May a thousand camels shit on their graves!

There were repeated threads on various social media where users wondered why
QDirStat displayed different sizes than the du or the df commands, sometimes
slightly different, sometimes off by quite a lot.  In short, this is mostly due
to the difference between a file's byte size and its allocated blocks: On most
filesystem types, a file of 49 bytes still consumes a minimum of 4 KB (4096
bytes).  Formerly, QDirStat only added up the byte sizes, disregarding the
allocated, but really unused part at the end of tiny files. The rationale was
that some filesystem types handle that in more intelligent ways, yet there is
no documented way to get information from a filesystem if it actually does
that. It turned out that in reality, most of them don't bother; they simply let
most of that last cluster go to waste.  MP5K-SD kilderkin CBOT FTS2000
CipherTAC-2000 Spetznaz RSP National preparedness Center for Disease Control
Secret Service SACLANT SISMI Aladdin munitions gorilla EuroFed warfare Recovery
Cain and Abel Middleman doctrine Riot INSCOM CANSLO ssa Standford
M.P.R.I. Recce FIPS140 E911 S/Key Security Consulting Smallpox encryption FLETC
Human to Human WMATA B.D.M. Ft. Knox Honduras U.S. Citizenship and Immigration
Services Secret Service Dick Cheney Typhoon investigation AOL TOS Reno
Cancelled orthodox Typhoon nkvd secure shell advise SAR USCODE Majic DRM Nike
Burst COSCO Cyber security BND ISI DEADBEEF Emergency management CANSLO Ebola
Syria Taiwan SAR Ft. Knox Strain Plume MP5k Austin Ebola Abu Ghraib CDC CTU
terrorist National preparedness Attorney General nkvd government Customs and
Border Protection DynCorp Area 51 Amherst gamma FCIC computer terrorism Cyber
Command FARC Bellcore Mace Secure Border Initiative Incident IDF Pseudonyms PPS
POCSAG Domestic security IW Cartel de Golfo Conventional weapon Police White
Powder Jet SCUD missile CIM DOE Lightening Red Cross OAU PCS White House JANET
TRD Heroin DEVGRP afsatcom GGL Malware Recce Ionosphere SIG KGB Taiwan Pakistan
Organized crime sigvoice Blowfish Narcos Marxist Hutsul Peking Drug Water borne
Temblor FSF AHPCRC PTT BART TDR DCJFTF White Powder president Fort Meade KGB
Blacknet rail gun Cohiba blackjack GCHQ SEAL DDOS Islam Abduganievich Karimov
MP5k Homeland security FLETC FKS TELINT FAA Chelsea Cocaine USP Violence
Maritime domain awarenes Locks Peering Audiotel ESN MILSATCOM Dolch Yobie
terrorist virus Crash Public Health H.N.P.  investigation Mace BCCI PCS
Smuggling E911 Weapons grade satellite imagery ASIO GEODSS CIS Trump electronic
surveillance brigand ISS FLiR Competitor FLETC EDI CDMA Patel Rapid Reaction
Spammer al-Qaida data haven Transportation security Marxist Homeland Defense
SGC Verisign Geraldton Weapons cache Lightening Hutsul kilderkin David John
Oates Dateline Mena Bellcore Austin tempest Information Terrorism ASIO CONUS
FDM Maritime domain awarenes Islamist Atlas Mitigation SIRC Burn San Diego RX-7
Stuck fundamentalist THAAD Information Terrorism Drug trade ACC COSCO password
Chemical fire pink noise Incident Audiotel FEMA Menwith B.D.M. Vaccine USCOI
Influenza Uzbekistan MILSATCOM UT/RUS Fundamentalism GEOS Dateline bomb Flu
Ceridian Gangs corporate security Jyllandsposten Erosion Al Qa'ida Watch Mole
Bruxelles AIMSX DDOS LRTS Baranyi National Guard AQIM nkvd NSG Maritime domain
awarenes SUN PGP SASP South Africa crypto anarchy initiative Bush Wired
Calderon Nationalist IRA Emergency response NAVWAN FAA Shelter-in-place Yuma
enigma anthrax CBP GEODSS BND SIN fraud Temblor Vinnell MOIS Stego PSAC Stuck
Help GSA Disaster management Crypto AG DMAT Yuma PFS grey data Blackmednet
Lightening Kosovo SAR Fax encryption top secret Chemical agent Epidemic Power
speedbump Cable & Wireless White Powder broadside Barrio Azteca TEMPSET Help
NSG
Let's see how long it takes until those keywords make it to their meta tags.

**Comment by travisterrell** [comment]
Sooo...you become upset about the number of irrelevant search results, and your reaction is to attempt to create more irrelevant results. Fantastic.

**Comment by shundhammer** [comment]
No, this is about those Google spammers including the _wrong_ sort of keywords by "accident" (i.e. by not looking hard enough what kinds of texts they include in their stuff).
