### ISSUE TITLE
Howto change shortcut Super+e to start qdirstat 

### ISSUE THREAD

**Issue by JohnML1** [shundhammer/qdirstat#152]
i'm on Deepin linux (Debian based) and qdirstat took super+e that used to be open dde-file-manager. 
I want to reassign this shortcut but its not possible with Deepin tools. 
So where is that setting written to?

**Comment by shundhammer** [comment]
You mean: While QDirStat is _not_ running, `Super` + `E` (i.e. `Win` + `E`) starts it?

That would be configured somewhere in your desktop. QDirStat has no part of that, that's purely a matter of the desktop; in your case obviously Deepin.

**Comment by shundhammer** [comment]
https://defkey.com/deepin-linux-shortcuts confirms that this key combination should start the file manager; but maybe there is a way in Deepin to configure what the default file manager is. I don't know; I don't use that desktop.

**Comment by shundhammer** [comment]
Maybe check here:

https://classicforum.manjaro.org/index.php?topic=30189.0
