### ISSUE TITLE
 Provide option to disable compressed man page

### ISSUE THREAD

**Issue by ConiKost** [shundhammer/qdirstat#156]
Hi!
In Gentoo, we never install compressed man pages, as this job is done through our package manager emerge. The user can set a custom format, in which all installed man pages are compressed after installation.

So it would be nice, if there is some switch, which makes it possible to install uncompressed man pages instead.

Thanks!

**Comment by shundhammer** [comment]
Well, all the other build systems _require_ me to add that stupid `gzip` step (not that I like that).

How about you add a small patch for your distro that fixes this for that .pro file?

I am very reluctant to change that man.pro yet again after I finally got it to work; it would always either do nothing or throw an error during building. This kind of task seems to be ill-supported by qmake; any minor change is likely to break it again.

**Comment by ConiKost** [comment]
Well, I can do that. I already patched it out for myself and bumped to 1.7.1 in Gentoo.
`sed -e '/gzip/d' -e 's/.gz//g' -i man/man.pro`

But it would me much more nice, if there would be a parameter to override that instead patching it. It's up to you :-)

**Comment by shundhammer** [comment]
It should work with this:

```patch
[sh @ balrog] ...src/qdirstat/man 82 % git diff
diff --git a/man/man.pro b/man/man.pro
index 2357a53..482b256 100644
--- a/man/man.pro
+++ b/man/man.pro
@@ -13,11 +13,10 @@ MAN_TARGET   = qdirstat.1.gz              \
 
 MAN_PATH     = $$INSTALL_PREFIX/share/man/man1
 
-man.files    = $$MAN_TARGET
+man.files    = $$MAN_SRC
 man.path     = $$MAN_PATH
 man.extra    = \
-       gzip --keep --force $$MAN_SRC; \
-       install $$MAN_TARGET $(INSTALL_ROOT)$$MAN_PATH
+       install $$MAN_SRC $(INSTALL_ROOT)$$MAN_PATH
 
 # The INSTALL_ROOT environment variable is used for rpm builds in the spec file
 # to allow for a build root that is separate from the system directories:
@@ -25,4 +24,3 @@ man.extra    = \
 #   make install INSTALL_ROOT=%{buildroot}
 
 INSTALLS    += man
-QMAKE_CLEAN += $$MAN_TARGET

```

**Comment by shundhammer** [comment]
Since I am glad that I have _one_ version that actually works in all the target environments that I have available, I don't think it's realistic to add another dimension of complication, so please use the above patch.

I don't know how that works in Gentoo, but in RPM or DPKG (.deb) based distros you have a _pristine_ upstream source tarball and then apply patches (diffs) on top of that; as many as you need to make things work on your target distro. I hope in Gentoo it's similar. ;-)
