### ISSUE TITLE
Show unpackaged files: Exclude `/snap` directory

### ISSUE THREAD

**Issue by stdedos** [shundhammer/qdirstat#157]
Nowadays, Ubuntu is implementing more and more logic around snap installations.

While technically they are unpackaged (from `dpkg`s point of view), they have their own packing logic.

**Comment by shundhammer** [comment]
`/snap` _is_ excluded from that view in the default settings:

https://github.com/shundhammer/qdirstat/blob/master/src/UnpkgSettings.cpp#L85-L95

But once you used that view for the first time, the setting is written to your `~/.config/QDirStat/QDirStat.conf` file, and the next time you use it, it uses the values from there.

Getting this back to the (now changed) defaults is what that "Restore Defaults" button in this dialog is all about:

![QDirStat-show-unpkg-dialog](https://raw.githubusercontent.com/shundhammer/qdirstat/master/screenshots/QDirStat-show-unpkg-dialog.png)

If you click on it, you will find that `/snap` is now excluded.

**Comment by shundhammer** [comment]
BTW I toyed with the idea of adding _snap_ as a full-fledged package manager to QDirStat; but the "Packages" view for it would degenerate to a `qdirstat /snap`, and it would not make any sense to have an "Unpackages Files" view for it because by definition everything in a loop-mounted snap image is part of that snap package.

**Comment by stdedos** [comment]
Oops :-D

Outdated version 😖

**Comment by shundhammer** [comment]
No, not really outdated version; you would not have seen `/snap` in that list with the latest version if you ever used that view before. This is a limitation of Qt's config file concept. If you have a config file that you used for a long time, you won't ever get thet defaults for anything unless you delete that config file.
