### ISSUE TITLE
"Insufficient permissions" message does not disappear

### ISSUE THREAD

**Issue by stdedos** [shundhammer/qdirstat#158]
Small bug; if you think that you can "easily fix" it, feel free.

1. `chown` a random (empty) directory to `root:root` (e.g. `~/.cache/doc`)
2. `$ qdirstat ~`
3. **While `qdirstat` still scans `~`**, after the message arrives, go ahead and fix it
	1. `sudo chown "${USER}:${USER}" ~/.cache/doc`
	2. On `qdirstat`, select the directory and press F6
4. `qdirstat` finishes scanning (optional?)

Actual:
1. Message "Insufficient permissions" persists (but "Details ..." view is empty), and
2. `.caches` is still red (but not `doc`)

Expected: None of the above

**Comment by shundhammer** [comment]
That status is kept for each subtree, and it is cascaded up the tree; but there is no information exactly where it happened without traversing the complete tree.

The simplest way is to re-read the complete tree.
