### ISSUE TITLE
scroll to selection sometimes fails

### ISSUE THREAD

**Issue by buxit** [shundhammer/qdirstat#16]
this is minor:

when clicking around in the treemap the listview on top sometimes does not scroll to correct position to make the selected item visible. i'm not sure what exactly it depends on. i can mostly get back to the right item by selecting a different rectangle and then selecting the intended rectangle again. selecting something on the very bottom right and then coming back towards top-left improves the chances of the intended selection getting visible in the list view.

**Comment by shundhammer** [comment]
I've seen that, too, but only with the latest Qt 5.5 on openSUSE / TumbleWeed. I can only guess that this is a problem introduced by SUSE patches. It seems to work on Kubuntu 14.04 LTS with the older Qt 5.2.

Which distribution and what Qt version are you using?

**Comment by buxit** [comment]
I'm using Arch Linux, which is currently on Qt 5.6.0 and has patches only for ALSA and QtDBus (see https://projects.archlinux.org/svntogit/packages.git/tree/trunk?h=packages/qt5-base).

**Comment by buxit** [comment]
consider merging PR #17

**Comment by shundhammer** [comment]
Yes, this fixed it. Thanks for contributing!
