### ISSUE TITLE
How to build with optimizations? (`-O2`, `-O3`)

### ISSUE THREAD

**Issue by EFanZh** [shundhammer/qdirstat#160]
It seems that the command line `qmake && make` does not enable compiler optimizations, how can I build qdirstat with compiler optimizations enabled?

**Comment by shundhammer** [comment]
```console
sh@balrog:~/src/qdirstat$ git clean -dfx
sh@balrog:~/src/qdirstat$ qmake
Info: creating stash file /ssd-work/home/sh/src/qdirstat/.qmake.stash
sh@balrog:~/src/qdirstat$ make
cd src/ && ( test -e Makefile || /usr/lib/qt5/bin/qmake -o Makefile /ssd-work/home/sh/src/qdirstat/src/src.pro ) && make -f Makefile 
make[1]: Entering directory '/ssd-work/home/sh/src/qdirstat/src'
/usr/lib/qt5/bin/uic file-details-view.ui -o ui_file-details-view.h
/usr/lib/qt5/bin/uic message-panel.ui -o ui_message-panel.h
/usr/lib/qt5/bin/uic main-window.ui -o ui_main-window.h
...
...
/usr/lib/qt5/bin/uic unreadable-dirs-window.ui -o ui_unreadable-dirs-window.h
g++ -c -pipe -Wno-deprecated -Wno-deprecated-declarations -g -Wall -W -D_REENTRANT -fPIC -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I.moc -isystem /usr/include/libdrm -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o .obj/main.o main.cpp
g++ -c -pipe -Wno-deprecated -Wno-deprecated-declarations -g -Wall -W -D_REENTRANT -fPIC -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I.moc -isystem /usr/include/libdrm -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o .obj/ActionManager.o ActionManager.cpp
```

**Comment by EFanZh** [comment]
I am not sure I understand. The compile command lines above do not contain [optimization flags](https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html), so the compiler optimization is not enabled.

**Comment by shundhammer** [comment]
Yes, I am still gathering information. I am also confused. ;-)

**Comment by EFanZh** [comment]
Is this related? https://github.com/shundhammer/qdirstat/blob/0b75489657312370db377d4b90f27b8c7a858a0d/src/src.pro#L15.

**Comment by shundhammer** [comment]
https://stackoverflow.com/questions/2987062/configuring-the-gcc-compiler-switches-in-qt-qtcreator-and-qmake

https://doc.qt.io/qt-5/qmake-variable-reference.html#qmake-cxxflags

> QMAKE_CXXFLAGS
> 
> Specifies the C++ compiler flags for building a project. The value of this variable is typically handled by qmake or qmake.conf and rarely needs to be modified. The flags specific to debug and release modes can be adjusted by modifying the QMAKE_CXXFLAGS_DEBUG and QMAKE_CXXFLAGS_RELEASE variables, respectively.

**Comment by shundhammer** [comment]
Now it would be interesting to see if this really makes a difference.

**Comment by EFanZh** [comment]
I think this issue can be closed now. Thank you for your quick response.

**Comment by shundhammer** [comment]
If you have some time, I'd be interested to hear some benchmark results.
