### ISSUE TITLE
"Press Enter to Open File" does not work

### ISSUE THREAD

**Issue by stdedos** [shundhammer/qdirstat#161]
Hello there,

And apologies for using this medium to ask my question!
(You may opt-in to "discussions", if you'd like "Issues" this these to branch out)

I cannot seem to able to trigger

```conf
[Cleanup_04]
Active=true
AskForConfirmation=false
Command=xdg-open %p
Hotkey=Enter
OutputWindowAutoClose=false
OutputWindowPolicy=ShowAfterTimeout
Recurse=false
RefreshPolicy=NoRefresh
Title=Open Item
WorksForDir=true
WorksForDotEntry=false
WorksForFile=true
```

using "Enter".

I always need to Right-Click > Open Item instead.

I don't know how to diagnose this; any information is welcome.

1.7.1.01-git, compiled in Ubuntu Focal, qt 5.12.8

**Comment by shundhammer** [comment]
I am pretty sure this is simply the way Qt handles those application-global action shortcut keys.

The "Enter" key is typically already taken by other actions, such as activating a dialog's default key. Come to think of it, I guess the same is true for normal alphanumeric keys like A..Z, a..z, 0..9; in general, probably all the keys that produce a character in an input field. I don't think any of those can be used to activate a global application action.

The function keys F1..F12 (except F10 which activates the main menu) and some very few others like "Insert" and "Delete" are probably the only ones that can be used for this without any modifier key (Ctrl, Alt; not sure if the Windows keys work here). For all other keys, you will need a modifier to avoid clashes with normal keys. And for some keys (cursor keys? Home / End / PgUp / PgDn) probably not even that will work.

**Comment by shundhammer** [comment]
I guess the "Enter" / "Return" key is caught by one of the widgets in the main window, and that key event is then considered as completely handled and not propagated any further. Probably it's the tree widget which usually has the keyboard focus.

Try a combination with a modifier key, e.g. `Ctrl+Enter` or `Alt+Enter`.

**Comment by shundhammer** [comment]
Gotcha:

https://doc.qt.io/qt-5/qabstractitemview.html#activated

This is in the QTreeView's parent class, the QAbstractItemView. It will catch the `Enter` key and emit the _activated_ Qt signal.

And if the keyboard focus is in another widget like the menu bar or on a tool bar button, they _all_ tend to handle that key in some way or the other. For that reason alone it's not a good idea to use the `Enter` key for activating a cleanup action.
