### ISSUE TITLE
Breadcrumbs Navigator too Wide for Very Long Paths

### ISSUE THREAD

**Issue by stdedos** [shundhammer/qdirstat#169]
For a very long path (586 chars), qdirstat is unable to be vertically collapsed, because of the sheer size of the path eyeballed.

It would be nice if there was some way to trim that path down e.g. by ellipsizing individual components and/or  omitting start/middle components.

**Comment by shundhammer** [comment]
That exists if you disable "auto column size" for that column.

I know the problem; in particular with those crazy long Git-object file names. But there is no easy solution: Introducing a general max width even with auto-width on would be very problematic. How wide should that column be allowed to become? And how would a user be able to see the full path, if desired?

Max width as wide as the screen; minus something (how much?) for the other columns? I don't know.

**Comment by stdedos** [comment]
My bad 😀

I was talking about the navigatable top row (i.e. just _above_ the Tree view), not the list columns

**Comment by shundhammer** [comment]
Ah, the breadcrumbs widget? Okay, that's something different.

Yes, that could definitely use some eliding if it gets too long. I'll check.

**Comment by shundhammer** [comment]
https://github.com/shundhammer/qdirstat/commit/ed2f6c6cbd07808a93211149bcec6a8581af5615 is a first fix, but I don't like it very much: It's too simplistic. When the path length is beyond the threshold, it aggressively shortens all path components, even if it would be sufficient to shorten just the longest ones.

![breadcrumbs-shortened](https://user-images.githubusercontent.com/11538225/123241624-99eb5900-d4e1-11eb-90f1-cb7720751f7a.png)


I'll probably refine that some more in the near future, but it should fix your current problem.

**Comment by shundhammer** [comment]
It's now less aggressive: If the total width is beyond the threshold, it will no longer shorten just every component to 16 characters; instead, it will pick the longest components first (but now including the leftmost non-clickable path, too) and stop shortening when the total width is below the threshold again.

![QDirStat-long-paths-02](https://user-images.githubusercontent.com/11538225/123492702-8db6e700-d61a-11eb-8f21-4f7b978bee28.png)
