### ISSUE TITLE
Wrong Allocated Size for Sparse Files if Read from Cache File

### ISSUE THREAD

**Issue by spacekpe** [shundhammer/qdirstat#184]
Hello,

and thank you for an awesome software and all the work you put into it over the years!

Here is a bug report about the latest version:

Version:
- qdirstat 1.8
- qt5-base 5.15.2

Observed behavior:
- Sparse files are detected correctly when scanning filesystem from GUI
- Apparent and allocated sparse file sizes seem to be written correctly to .qdirstat.cache.gz file generated from GUI
- GUI displays incorrect Allocated size when reading cache file generated by itself

Reproducer:
- generate sparse file
```
dd if=/dev/zero of=sparse count=1 seek=100 bs=1M
```
- generate cache file of the directory either in GUI or using
```
qdirstat-cache-writer .
```
- load the cache file into the GUI

- Screenshot of "live scan" - sizes are okay: 
![screenshot-ok-live](https://user-images.githubusercontent.com/2099568/145718802-b253b8da-17d0-4dfe-bdbd-53303208d0ea.png)

- Screenshot of cache read - allocated size is incorrect: 
![screenshot-bad-cache](https://user-images.githubusercontent.com/2099568/145718817-ab4662f1-441a-4e12-901e-9a171a82480a.png)

- cache file to reproduce the problem:
[.qdirstat.cache.gz](https://github.com/shundhammer/qdirstat/files/7699025/default.qdirstat.cache.gz)

Please let me know what other information you need.

**Comment by shundhammer** [comment]
You are right.

For a moment I thought it's a problem of the cache writer to write incorrect numbers of blocks to the cache for sparse files, but AFAICS that's actually correct:

```
[sh @ balrog] ~/tmp 6 % zcat work-test-sparse.cache.gz
[qdirstat 1.0 cache file]
# Do not edit!
#
# Type	path		size	mtime		<optional fields>

D /work/test/sparse	4K	0x5ee8e19d
F	sparse-8k-zero	8K	0x5ee8e19d	blocks: 0
F	sparse-8k	8K	0x5ee8e1a2	blocks: 8
F	sparse-zero.bin	1000M	0x56b499f6	blocks: 0
F	sparse-1MB.bin	1001M	0x56b49a1c	blocks: 2048
```

(Using the `sparse/` subdirectory from QDirStat's test data at https://github.com/shundhammer/qdirstat/tree/master/test/data)

![work-test-sparse-live](https://user-images.githubusercontent.com/11538225/145720122-6f94988b-c976-401f-8e02-a0c95c313d4a.png)

Reading back those data from a cache file shows "allocated: 0 Bytes" for all sparse files which is wrong for `sparse-8k` and `sparse-1MB.bin`:

![work-test-sparse-cached](https://user-images.githubusercontent.com/11538225/145720154-704bf537-128b-406a-8362-a25dd1483812.png)

Good catch!

**Comment by shundhammer** [comment]
This affects only sparse files when read from a cache file. Non-sparse files are displayed correctly.

**Comment by shundhammer** [comment]
The fix was adding the missing case in the _FileInfo_ item constructor for cached items: If there is a `blocks:` field, it is now correctly used to initialize the `_allocatedSize` field.

![cached-sparse-files-fixed](https://user-images.githubusercontent.com/11538225/145721354-b8a7dc0f-a137-495c-823c-95f1ddc37789.png)

Petr, thanks for finding and reporting this!

**Comment by spacekpe** [comment]
Wow, thank was fast! Thank you!
