### ISSUE TITLE
Feature Request: dark mode

### ISSUE THREAD

**Issue by chabala** [shundhammer/qdirstat#186]
I would like to be able to toggle the colors of the application to be light text on dark backgrounds.

I see there have been some requests for icon theme changes, but I would be interested in a more general dark mode. If the icons have to stay the same, so be it.

**Comment by shundhammer** [comment]
Like in all Qt applications, the widget theme is taken from your desktop. So if you use any desktop that can propagate its theme to Qt applications, it will work wit QDirStat as well.

<img src="https://raw.githubusercontent.com/shundhammer/qdirstat/master/screenshots/QDirStat-err-dirs-light.png">

<img src="https://raw.githubusercontent.com/shundhammer/qdirstat/master/screenshots/QDirStat-err-dirs-dark.png">

**Comment by chabala** [comment]
Thanks for the hint. Turns out I was just missing `qt5-style-plugins`, and now QDirStat matches my dark system theme.

**Comment by BinaryQuantumSoul** [comment]
For those in the same situation (GNOME):
`sudo apt install qt5-style-plugins qt5ct`
`export QT_QPA_PLATFORMTHEME=qt5ct`
`qt5ct` > select gtk2 theme
