### ISSUE TITLE
Mime types not respected with overlapping patterns

### ISSUE THREAD

**Issue by maarten-k** [shundhammer/qdirstat#190]
Qdirstat categorizes *.gz as a compressed file and a tar.gz as a compressed archive when looking at the mime categories. However, in practice, these files are both categorized as compressed files.  The same problem also occurs with user-defined Mime types. 

Minimal reproducible example:
```
mkdir test
cd test
echo "test" > test.tar.gz
echo "test" > test.gz
qdirstat .
```

**Comment by shundhammer** [comment]
Yes, you are right. Thank you for reporting this!

**Comment by shundhammer** [comment]
Argh.

It did find the category for the longer one (`.tar.gz`), but then it continued looking, resulting in the shortest matching one (`.gz`). Now stopping at the longest hit.
