### ISSUE TITLE
error qdirstat-cache-writer Can't locate URI/Escape.pm in @INC (you may need to install the URI::Escape module)

### ISSUE THREAD

**Issue by clach04** [shundhammer/qdirstat#196]
Error running `qdirstat-cache-writer`:

    Can't locate URI/Escape.pm in @INC (you may need to install the URI::Escape module) (@INC contains: /etc/perl /usr/local/lib/arm-linux-gnueabihf/perl/5.24.1 /usr/local/share/perl/5.24.1 /usr/lib/arm-linux-gnueabihf/perl5/5.24 /usr/share/perl5 /usr/lib/arm-linux-gnueabihf/perl/5.24 /usr/share/perl/5.24 /usr/local/lib/site_perl /usr/lib/arm-linux-gnueabihf/perl-base) at ./qdirstat-cache-writer line 53.
    BEGIN failed--compilation aborted at ./qdirstat-cache-writer line 53.

Fix appears to be to install `URI::Escape` via:

    cpan URI::Escape

Which contradicts the docs:

  * https://github.com/shundhammer/qdirstat/blob/master/scripts/README.md?plain=1#L10
  * https://github.com/shundhammer/qdirstat/blob/master/doc/QDirStat-for-Servers.md?plain=1#L13

From a quick scan of the script, `uri_escape` is being used, potentially could be replaced with something else?

**Comment by shundhammer** [comment]
There was a discussion about this some time in the past. The outcome was that it's not a good idea to cook one's own for things like that; in particular URL escaping is a lot less trivial than it seems, and that might be a security-relevant thing, and it should be well tested and maintained.

But I think documenting this as you did in your pull request is the reasonable approach. Personally, I'd consider `URI::Escape` part of a "normal" Perl installation; this is in wide use by a lot of Perl code. But of course YMMV, and it tends to change over the years how much (or how little) of all the CPAN modules are commonly installed by default, and of course across distributions.
