### ISSUE TITLE
Support for analyzing space usage in root locations

### ISSUE THREAD

**Issue by soredake** [shundhammer/qdirstat#198]
It would be nice if qdirstat supported analyzing space usage in root locations like /root. Maybe [polkit ](https://ru.wikipedia.org/wiki/Polkit) can help with this.

Related:
https://invent.kde.org/frameworks/kio/-/merge_requests/731

**Comment by shundhammer** [comment]
Simply use `sudo`. That's what it's there for, without all the crazy hoops to jump through.

**Comment by shundhammer** [comment]
If you are using one of those Linux distros where they killed the usability of `sudo` for alleged better security, you may want to re-enable keeping the environment variables in `/etc/sudoers` where they might actively sabotage your work environment:

https://github.com/shundhammer/huha-linux-tips/blob/master/doc/ubuntu-tips.md#keep-the-shell-environment-during-sudo

I consider this antisocial default configuration giving the users the finger, and it's one of the first things that I fix on a freshly installed machine.
