### ISSUE TITLE
Some out dated stuff about k4dirstat in the README

### ISSUE THREAD

**Issue by jeromerobert** [shundhammer/qdirstat#2]
k4dirstat is ported to Qt5 / KF5 and no longer use any Qt3 nor Qt4 backward compatibility stuff. So the README is about an old version of k4dirstat.

**Comment by shundhammer** [comment]
Jerome,

thanks for the information. I'll update the README immediately. I had simply installed the sources with apt-get source. Come to think of it, that was just stupid; I'm using Kubuntu 14.04 LTS here. I should have thought about there being a newer version of k4dirstat out there.

Thanks for the information!

**Comment by shundhammer** [comment]
Fixed.
