### ISSUE TITLE
egrep in script prints to stderr

### ISSUE THREAD

**Issue by a1346054** [shundhammer/qdirstat#201]
For your information `egrep` and `fgrep` now emit an error to stderr

https://lists.gnu.org/archive/html/info-gnu/2022-09/msg00001.html

related:

https://github.com/shundhammer/qdirstat/pull/179/commits/ac14a824164ae4a778faf0e5f55cda6f88cfa30c#r716073897

**Comment by shundhammer** [comment]
What scripts and what errors? Please be more specific.

**Comment by shundhammer** [comment]
Also, what version of `grep`? A new one where the GNU people are again giving the finger to everybody working with the tools, claiming that something as ancient and as basic as `fgrep` might go away; which will clearly *never* happen because that would break a gazillion of scripts?
