### ISSUE TITLE
Yellow font color in directory tree

### ISSUE THREAD

**Issue by wanageeska** [shundhammer/qdirstat#202]
Hi,
Some level of my directory tree use a yellow font. (See attached screenshot.) Is this normal behaviour or have I accidentally toggled something? I have used qdirstat in the past and can't recall ever seeing yellow font in the tree.
Thanks,
W
![image](https://user-images.githubusercontent.com/17569679/189820317-c3c521a8-8e8e-436b-b23e-c1ba4fb1daba.png)

**Comment by shundhammer** [comment]
It looks like your color theme was identified as a dark one; only then it will choose that yellow font.

Please try to move away your QDirStat configuration files (while QDirStat is not running!) and try again:

```
cd ~/.config
mv QDirStat QDirStat.old
```

Does this change anything?

To get back to that old configuration:

```
cd ~/.config
mv QDirStat.old QDirStat
```

**Comment by shundhammer** [comment]
When I look at the code I think you might have used QDirStat previously with a dark theme, and it saved that text color; and now you are using a light theme, and the color is still the one from the dark one. Does that sound realistic?

**Comment by shundhammer** [comment]
Relevant code:

https://github.com/shundhammer/qdirstat/blob/master/src/DirTreeModel.cpp#L127-L132

```C++
bool DirTreeModel::usingDarkTheme()
{
    QColor background = qAppPalette().color( QPalette::Active, QPalette::Base );

    return background.lightness() < 128; // 0 (black) .. 255 (white)
}
```

**Comment by shundhammer** [comment]
```Console
[sh @ balrog] ~ 15 % grep -B 3 -A 1 "SubtreeReadErrColor" ~/.config/QDirStat/QDirStat.conf

[TreeTheme-dark]
DirReadErrColor=#ff0000
SubtreeReadErrColor=#ffff00

[TreeTheme-light]
DirReadErrColor=#ff0000
SubtreeReadErrColor=#a00000
```

`SubtreeReadErrColor=#ffff00` is that yellow color, but it should be used only with a dark color theme and only if there were read errors (mostly due to insufficient permissions) in that directory subtree.

**Comment by shundhammer** [comment]
So, did I try what I suggested in my first comment? Did it help?

**Comment by shundhammer** [comment]
No response.

**Comment by wanageeska** [comment]
Hi @shundhammer, sorry I haven't had internet. I applied your first suggestion and it fixed the issue. I haven't had a chance to investigate what caused the problem but I have a suspicion that Yin-Yang (https://github.com/oskarsh/Yin-Yang) might have played a role. Thanks for your help--much appreciated!

![image](https://user-images.githubusercontent.com/17569679/190828577-49e01355-7a8c-454e-8dc9-e0c4158d95c0.png)

**Comment by shundhammer** [comment]
OK, glad to hear that you got the problem fixed.

Why it happened - I don't know. If you don't habitually manually edit those config files, it might be Evil Earth Spirits or an unlucky constellation of the zodiac. ;-)
