### ISSUE TITLE
Method used to draw the bottom grid of file sizes

### ISSUE THREAD

**Issue by khzind** [shundhammer/qdirstat#203]
Hello brother,

Below the qdirstat window,  There is a bottom grid showing file sizes shown using treemap - F9 menu

What logic is used to draw this tree map ?

Best Regards,

**Comment by shundhammer** [comment]
What it is:

- https://github.com/shundhammer/qdirstat#old-features

  > - Treemap display. Treemaps are a way to visualize hierarchical data structures, invented by Ben Shneiderman. Basically, the hierarchy is flattened and each level grouped in a rectangle, inside which it is again subdivided in rectangles. The area of each rectangle corresponds to the size of each item or subdirectory. For the purposes of QDirStat, it is enough to know that a large blob corresponds to a large file; you can instantly see where large ISOs or movies are.

- https://www.mankier.com/1/qdirstat#The_Treemap
- https://en.wikipedia.org/wiki/Treemapping
- https://datavizcatalogue.com/methods/treemap.html

How it's drawn:

- https://github.com/shundhammer/qdirstat/blob/master/src/TreemapView.h
- https://github.com/shundhammer/qdirstat/blob/master/src/TreemapView.cpp
- https://github.com/shundhammer/qdirstat/blob/master/src/TreemapTile.h
- https://github.com/shundhammer/qdirstat/blob/master/src/TreemapTile.cpp

See also those papers from the TU Eindhoven:

- Cushion tremaps: https://www.win.tue.nl/~vanwijk/ctm.pdf
- Squarified treemaps: https://www.win.tue.nl/~vanwijk/stm.pdf
