### ISSUE TITLE
F3 view is not capable of showing files without extension

### ISSUE THREAD

**Issue by C0rn3j** [shundhammer/qdirstat#205]
Reproduction:

1)
```
mkdir /tmp/test
touch /tmp/test/test.jpg
touch /tmp/test/test
qdirstat /tmp/test
```
2) F3
3) Doubleclick on .jpg, file shows fine
```
2022-12-16 11:15:15.376 [234324] <Debug>   LocateFileTypeWindow.cpp:112 populate():  Locating all files ending with ".jpg" below /tmp/test
2022-12-16 11:15:15.376 [234324] <Debug>   LocateFileTypeWindow.cpp:122 populate():  1 directories
```
4) Doubleclick on \<no-extension\>
```
2022-12-16 11:15:18.283 [234324] <WARNING> FileTypeStatsWindow.cpp:346 currentSuffix():  NO_SUFFIX selected
```
and nothing happens in the UI

**Comment by shundhammer** [comment]
This is by design, as discussed ad nauseam when that whole "view by file type / extension" discussion started.

This has been and will always be limited to files where a clear file type can be determined; those that have an extension. Those that don't have one (i.e. the great majority of all files on a Linux system, anywhere from 35% in a home directory to 50% on a root filesystem) are not suitable for those actions.

That was the accepted compromise to start doing those things in the first place.

You can easily see it by the fact that the "File Type" menu button at the bottom of the "File Type Statistics" (F3) window remains disabled until a specific extension is selected.

**Comment by C0rn3j** [comment]
I understand that it is not desired to have anything else other than `<No Extension>` for such files, but it would still be nice to be able to open a list of them.

I am currently working on a large directory with many different nested directories and lots of various files, and if there is a file type which is not detected by QDirStat as a separate category, it is 99% a broken file that I need to deal with.

Such files include things like a file named `mycoolpicture` that's actually a `.jpg` but someone managed to remove the extension, and that needs to be fixed, but currently I need to include voodoo `find` commands in my workflow because while QDirStat is able to inform me that these files exist, it is not able to show them to me.

I agree this feature would not be of much use when scanning against `/`, but that is not my use case.

**Comment by shundhammer** [comment]
In the normal case, that would result in a window with 30-50% of all files; because that's how many there normally are without extension.

If you have a very special case where you _know_ that every file should have an extension, it's a simple

```
find . -type f \! -name "*.*"
```

or, not POSIX compliant, but better readable:

```
find . -type f -not -name "*.*"
```

**Comment by C0rn3j** [comment]
That indeed does work for my above example and is exactly what I've been using in the case of extension-less files.

However there's also files that have weird extensions, but they do have an extension, so simple find like this does not work in those cases.

**Comment by shundhammer** [comment]
Sure, and then it gets more and more specialized, making it useful for less and less users.

**Comment by shundhammer** [comment]
Maybe what you really want is something to find "oddball" files.

Like, in a directory full of .jpg files, a few that are _not_ .jpg. Or in a directory full of .mp3 files, a few that are  .txt or .png (which might be legitimately there; album covers for example).

In general, in a directory that is almost completely homogenous with one file type, those that are the exception there. Those may be there intentionally; or there might have been a human error when renaming a file, a drag&drop accident, somebody starting a command in the wrong directory.

An action like that might find a home in the "Discover" menu. I am just not sure if there is a generic way to specify what it should do without being either too narrow or too wide.

**Comment by shundhammer** [comment]
This is a duplicate of issue #130.
