### ISSUE TITLE
Feature Request: Show difference in file count compared to last scan

### ISSUE THREAD

**Issue by alexanderdd** [shundhammer/qdirstat#212]
Hello @shundhammer !

I am looking for a way to see if something went wrong in a directory, whether someone accidentally removed a lot of files, or a whole directory full of files, or accidentally moved a whole directory.

qdirstat already shows the number of files in a tree, neat!

- Would it be possible to add another column "difference in file count (compared to last scan)"? 
- Or to implement a way to compare two cache files?
- Or, that would also help, "export current view as csv". (not the tree, that's not possible, and I read your opinion on csv in another issue.. still "current view" would be helpful)

(btw very useful program, it just helped me very efficiently to discover some files to delete)

**Comment by shundhammer** [comment]
I have a deja vu... I explained every single one of those before in great detail. ;-}

What you can easily do is store the result of a scan as a cache file and later load it in QDirStat, and start a new instance with a fresh scan; and then compare manually.

Other than that, a tree diff is a user interface nightmare; because all kinds of things may have changed, including complete subtrees missing, complete subtrees being new, and every single data column changed anywhere. And of course a combination of all that: A subtree moved to another branch, and individual columns changed.

I do not know a single diff tool that can do a good job at displaying tree diffs.

**Comment by shundhammer** [comment]
## Exporting to CSV

https://github.com/shundhammer/qdirstat/issues/182

**Comment by shundhammer** [comment]
## Comparing Disk Snapshots

https://github.com/shundhammer/qdirstat/issues/139

**Comment by shundhammer** [comment]
## File Age Statistics

Depending on your specific use case, maybe the _File Age Statistics_ (`F4`) view is useful for you:

https://github.com/shundhammer/qdirstat/issues/172

That shows you the files that were added or changed by month (for the last 13-24 months) and by years. If you simply want to know what's new during the last few months, this may be for you.

If you are interested in what was added or changed very recently, there is also "Discover" -> "Newest Files" in the menu. If that's your home directory, be advised that the Internet browsers with their gazillion files that they keep changing all the time will flood you with non-information, though.

**Comment by alexanderdd** [comment]
Thank you for taking the time to answer me. I would also have been ok with a link to a place where you already explained those things.

As I said, I understand the problems with tree diff, thats why I asked for "export current view as csv". But its not that important, I dont have the skills to turn such csv's into useful visuals anyway.

**Comment by brycenesbitt** [comment]
This basic feature: diff, has a lot of use cases.
And there's a related one: file comments.

I disagree that the diff needs to be presented in a way that's hard to generate.
A full tree diff, pretty hard, pretty messy.  The various visual diff programs are big in their own right.

But ultimately **QDirStat** has a long list linear list of files which have a name, size, flags and exist in a path.  A diff visualization could be a long linear list:

**_/home/users/Bryce/test1.txt [changed size][changed flags][changed modify date]
/home/users/Bryce/test2.txt [new]_**

With some sort buttons (e.g. size, age, newness, access date, modify date, etc) .  That alone could answer a variety of use cases, such as asking why my disk is more or less full than last time.
--------------------------------
The related feature is comments.  I may spend half an hour on a particularly large juicy looking directory only to determine I cannot delete it.  If I could write a note to myself comment, that QDirStat persists, that would be quite nice.  The note would expire if the path changes.

**Comment by brycenesbitt** [comment]
Linking to related issue https://github.com/shundhammer/qdirstat/issues/139
