### ISSUE TITLE
Collapsing/uncollapsing directories causes white flashes when using a dark theme

### ISSUE THREAD

**Issue by deadmeu** [shundhammer/qdirstat#217]
When using a dark theme (such as KDE's default Breeze Dark theme). Clicking on folders to collapse/uncollapse them causes the Subtree Percentage column to flash white during the expansion animation.

https://user-images.githubusercontent.com/12111013/232405655-758e3150-bce0-4684-bba7-85bc2a3983ee.mp4

QDirStat Version: 1.8.1
Operating System: Arch Linux 
KDE Plasma Version: 5.27.4
Qt Version: 5.15.9
Graphics Platform: Wayland

**Comment by shundhammer** [comment]
That's a problem of the underlying Qt libs.
