### ISSUE TITLE
The squarified tile layout doesn't match the original published paper

### ISSUE THREAD

**Issue by Lithopsian** [shundhammer/qdirstat#224]
The qdirstat algorithm for laying out squarified treemaps is subtly different from that described by Bruls et al (https://link.springer.com/chapter/10.1007/978-3-7091-6783-0_4).  I don't know if this was intentional or a happy accident back in pre-history that produced something that looking like it was working.

The current algorithm lays out tiles in rows along the longer side of the parent rectangle.  This produces a series of ever-narrower stripes along the rectangle, each with a series of hopefully near-equal near-squares.  It is prone to non-square tiles at the extremes of the long rows, and the last row in particular produces stretched tiles.  See the attached screenshot for an example.
![Screenshot_2023-11-16_18-29-20](https://github.com/shundhammer/qdirstat/assets/7702742/f26e179b-09f3-4ce4-a06d-b85d70e82811)

The current algorithm is prone to leaving empty space at the end of rectangles.  There are a number of reasons for this, and it isn't obvious when a minTileSize is set.  However, even with minTileSize=0, there can be empty space.  This is partly due to some rounding errors (much worse for the non-squarified code) and partly because the parent totalAllocatedSize doesn't match the sum of the children totalAllocatedSizes.  In this particular case (theme icons) there are a lot of symlinks which have zero allocated  space but do take up space. (totalSize is non-zero).
![Screenshot_2023-11-16_18-34-40](https://github.com/shundhammer/qdirstat/assets/7702742/5ba676ba-0a6c-4e2a-82a4-f54cd8648a59)

The exact algorithm described in the paper lays out each row along the shorter side of the parent rectangle.  This subtle difference means that the rows are shorter, the remaining space stays relatively square, and rows are laid out in roughly-alternating horizontal and vertical directions as the remaining space shrinks.  See an attached example, showing the same files as before (note that the shading has also been fixed, see my other issue).
![Screenshot_2023-11-16_18-29-42](https://github.com/shundhammer/qdirstat/assets/7702742/ab4e4629-86c1-4bdf-8ec1-7bdb08a36038)

**Comment by shundhammer** [comment]
First of all, thank you for taking the time to dig deep into this since it's a nontrivial area of QDirStat. The code and the algorithm go back until KDirStat 2.3.x from 2003; that's 20 years ago. While porting this from KDirStat / Qt 3 to QDirStat / Qt 5 I simply ported it from the old Qt 3 QCanvas to the new Qt 5 QGraphicsView without changing the algorithm.

It is very well possible that it wasn't an ideal approach. I vaguely recall that there were several different papers, all from the TU Eindhoven, and that I didn't follow their algorithm exactly; for what reason, I don't recall anymore, however.

**Comment by shundhammer** [comment]
## Allocated Size vs. Byte Size and Leftover Space

When I introduced different size methods in early 2020 with QDirStat 1.7 (see issue #134), there were some compromises to make: When and how to use allocated vs. byte size (the nominal size displayed by `ls -l`). Each one has its justification and its use case; but confronting users with _two different_ sizes everywhere would quickly overwhelm the average user, and it would make the user interface really unwieldy.

Hence the hybrid (some might say "muddled up") approach: For files, in most places the byte size is used; with some exceptions like sparse files (which are rare in today's Linux) and tiny files that  consume less than one cluster (typically 4k on most filesystems).

For directories and entire subtrees, the allocated sizes are used

**Comment by Lithopsian** [comment]
> First of all, thank you for taking the time to dig deep into this since it's a nontrivial area of QDirStat. The code and the algorithm go back until KDirStat 2.3.x from 2003; that's 20 years ago. While porting this from KDirStat / Qt 3 to QDirStat / Qt 5 I simply ported it from the old Qt 3 QCanvas to the new Qt 5 QGraphicsView without changing the algorithm.
> 
> It is very well possible that it wasn't an ideal approach. I vaguely recall that there were several different papers, all from the TU Eindhoven, and that I didn't follow their algorithm exactly; for what reason, I don't recall anymore, however.

Yes, kdirstat and even windirstat are exactly the same.  I was aware that a "more" squarified layout was possible and thought I'd have a look at how complicated it would be to use it in qdirstat.  The eureka moment when I realised it was essentially flipping one less-than to a greater-than made me suspect it was just an accident in the original coding.  Perhaps a minimal patch just so you can see the basic difference, keep your eyes peeled.

**Comment by shundhammer** [comment]
I'll experiment some with that. If it improves the treemap, I am all for it.

**Comment by Lithopsian** [comment]
Here's a basic patch for the squarification (named*.txt because github won't upload .patch files).  It includes some changes to scaling, but everything is still based on totalAllocatedSize().  I'll upload patches for the cushion highlighting on the other thread, but you'll get the best results by applying all the patches.
[TreemapTile.cpp.1.txt](https://github.com/shundhammer/qdirstat/files/13416118/TreemapTile.cpp.1.txt)
[TreemapTile.h.txt](https://github.com/shundhammer/qdirstat/files/13416123/TreemapTile.h.txt)

**Comment by shundhammer** [comment]
I just merged PR #225 into a new feature branch [better-tremap](https://github.com/shundhammer/qdirstat/tree/better-treemap) for parameter tweaking before merging that branch into _master_.

**Comment by shundhammer** [comment]
See also the summary in #236.
