### ISSUE TITLE
Treemap wheel zoom doesn't work when a tree is first built

### ISSUE THREAD

**Issue by Lithopsian** [shundhammer/qdirstat#226]
Normally, the mouse wheel will zoom in and out of the treemap even if no item is selected.  If there is no current item, it chooses the one under the mouse and goes from there.  When a treemap is first built, it looks like the current item is set to the root tile and no zooming is possible.  This is the very time when it is most likely that there will be no selected items.

**Comment by shundhammer** [comment]
That is right: If nothing is selected, you cannot zoom. Also if the root of the tree is selected because then you are already at the maximum zoom level.

Please notice that Qt selection widgets like the QTreeView make a difference between the _current_ item (the one with the keyboard focus in light blue) and a _selected_ item (dark blue). But even if the current item is not the root you can zoom in as far as that current item.

You can experiment with that with `Ctrl`-`click` on the selected item: That removes the selection in the tree view, and you will get a dotted line around the corresponding treemap tile.

**Comment by Lithopsian** [comment]
Yes, done all that.  Took me ages to work out why the wheel sometimes works and sometimes doesn't.  If there is no current item at all (you usually have to de-select manually, but there are times when the selection is lost for various reasons, such as minTileSize dropping the tile), then the wheel event handler picks the item under the mouse and zooms using that.  This is quite a nice feature, better than ignoring the wheel completely. Except that it doesn't work when the current item is set to the root tile, then you're just stuck unable to zoom at all with the wheel.  I can't think of any reason not to pick a tile and scroll, especially if the root tile has just been set as the current item,  not picked by the user.  Doubly since the highlight doesn't show when the selection is the root tile, so you have no idea it has been set to the current item - different issue?

Call it an enhancement request if you like.

**Comment by Lithopsian** [comment]
Still playing ... Refresh All builds the tree from scratch, drops all selections, leaves no current item, and zooms out to the top level.  Then zoom buttons are all greyed out.  Then, the mousewheel will zoom in by creating a current item under the mouse.

F6 while a file or <Files> is selected changes the selection and current item to the parent directory and zooms out if necessary.  I can see the case for Refresh All completely resetting the selection and zoom, but it is a bit disconcerting for Refresh Selected that seems like it should just see if anything has changed (just the selected or its parent as well?) but otherwise stay exactly where it was.

Further ... if a directory has disappeared (I deleted it!) when F6 is pressed, the message panel appears suggesting I might not have sufficient permissions.  The directory continues to be shown, with a size (and greater-than) even though it doesn't exist.

**Comment by shundhammer** [comment]
Summary: It is perfectly normal that you cannot zoom initially, because either nothing is selected or the root item, which means that the maximum possible zoom level is already reached.
