### ISSUE TITLE
Hard links are reported multiple times at their full allocated size

### ISSUE THREAD

**Issue by Lithopsian** [shundhammer/qdirstat#227]
When there are multiple hard links to a file, they should generally be reported with their size divided among all the links.  This doesn't happen and each is reported at full size, even when ignoreHardLinks is false.  I think a cached value is being pulled in by the column formatting instead of using the member function in FileInfo, so the hard link division doesn't get done.

**Comment by shundhammer** [comment]
There is one exception to that: NTFS filesystems.

The Linux driver for NTFS reported files twice if there was a long name and the old MS-DOS style 8+3 name; like `Program Files` vs. `PROGRAM~`. And that screwed up the whole calculation, so I had to switch that off for that filesystem type.

Please check the QDirStat log if the filesystem where you see that is detected as NTFS.

**Comment by shundhammer** [comment]
See also issue #88 .

**Comment by Lithopsian** [comment]
Don't think it is detecting as NTFS.  Log says 

> MountPoints.cpp:535 findNtfsDevices():  No NTFS devices found

The example I looked into in detail was /usr/bin/bzcat, which has three hard links (bzcat, bzip2 and bunzip2).  It shows as 38.3kB / 3 links for all three on my system, probably very similar on yours.  I'm 99% sure that is the actual file size, not one third of it.  du rather randomly shows bunzip2 as 39224 bytes and doesn't show the other two at all.

I've seen in the code where it divides by the number of links, added some debugging, and it wasn't getting hit when the columns were formatted for display.  It did get hit once earlier while the tree was being built.  The debug output showed 39k getting divided by three so that works, but it isn't being used for any output that I could find.

**Comment by shundhammer** [comment]
No, `/usr/lib/bzip2` does not have any hard links on my OpenSUSE Leap 15.5, `bzcat` and `bunzip2` are symlinks.

![bzcat](https://github.com/shundhammer/qdirstat/assets/11538225/a68b911f-52a0-476c-92d0-e5cd34a6ed5c)

**Comment by shundhammer** [comment]
There is a tarball with test data for such things in the source tree:

https://github.com/shundhammer/qdirstat/tree/master/test/data

**Comment by shundhammer** [comment]
I just created a 10 MB file with `if=/dev/zero of=hardlink-01 bs=1M count=10` and hardlinked it:

```
[sh @ balrog] .../work/test/hardlinks 32 % ls -lhi
total 30M
20316169 -rw-rw-r-- 3 sh users 10M 25. Nov 18:31 hardlink-01
20316169 -rw-rw-r-- 3 sh users 10M 25. Nov 18:31 hardlink-02
20316169 -rw-rw-r-- 3 sh users 10M 25. Nov 18:31 hardlink-03
```

(notice how `ls` is confused with those hard links)

![hardlinks-10MB](https://github.com/shundhammer/qdirstat/assets/11538225/9f92947c-2d30-4ad7-87ba-c5efa3f0cd3e)

I don't see anything wrong with what QDirStat reports here.

**Comment by Lithopsian** [comment]
I think I've misunderstood the hardlink accounting.  So the individual hardlinks all show at the full size, but the parent just gets the the fractional size?  So three times one third if they're all in the same same directory?  I do see that with the test data, slightly harder to tell with my /usr/bin directory.

**Comment by shundhammer** [comment]
The individual hardlinks each show the nominal full size and the number of links; I thought it was obvious with that equation-like notation "10.0 MB / 3 Links" (implying that this equals 3.33 MB).

Exactly which number is relevant for you depends on your individual use case, and where the other links are. If they are all in the same directory, you will get the correct total size for that directory, or when you want to make a backup of the directory.

If some of the links are outside that directory, and you want to make a backup, you will still need the disk space for the whole file, so the backup will be larger.

But it's pretty academic in real life since hard linked files are not very common anymore these days. Check your system with "Discover" -> "Files with Multiple Hard Links".
