### ISSUE TITLE
File details panel doesn't show correct data when opened

### ISSUE THREAD

**Issue by Lithopsian** [shundhammer/qdirstat#232]
The file details panel is not initialised or updated when it is opened.
1. Hide the file details panel.
2. Restart QDirStat.
3. Select a file.
4. Show the details panel.
The panel is blank.  Not too horrible, but a symptom of the problem.

For a worse case:
1. With the details panel visible, select a file.
2. Hide the panel
3. Select a different file.
4. Show the panel.
The panel still shows the details of the first file, not those of the currently-selected file.

**Comment by shundhammer** [comment]
Oops, you are right.

At first I thought this doesn't really happen too often, but then I realized it happens already when switching between one of the layouts that show the details panel (L1, L2) to the other one that doesn't (L3), so it really is important.

Fixed. Thank you!
