### ISSUE TITLE
Selected empty directories don't get the correct highlight

### ISSUE THREAD

**Issue by Lithopsian** [shundhammer/qdirstat#234]
1. Find some empty directories to play with, or create some.  These show with their allocated size in the treemap.
2. Select more than one of them.
The current item gets the correct solid red highlight, but the others get a black and white dotted highlight which I think is the Qt default rather than from QDirStat.

This seems to be a TreemapTile painter issue.  The highlight check is inside an if statement that excludes directories, so it never draws a highlight for them even if they are part of the selection.  Directories just get a simple paint with the pre-defined gradient or colour.

There is also an itemChange event handler that draws some highlights when an item's selection status changes.  It only draws for items that have children.  So one or the other could pick up the empty directories.  I tried putting it in paint() and that seemed to get called at all the appropriate times.

**Comment by shundhammer** [comment]
That's interesting. I've never seen that before.

...not that this is a real-world problem, of course.

**Comment by Lithopsian** [comment]
Just noticed something from looking at that paint function: the selection highlights are only drawn if cushion shading is configured.  All plain tiles get the black and white dotted outline.

**Comment by Lithopsian** [comment]
Yes, they are known to be selected, but TreemapTile::paint just doesn't paint highlights for empty directories.  Or any directories at all.  And itemChange() doesn't highlight anything that doesn't have children, presumably on the assumption that it has already been done in paint().

**Comment by shundhammer** [comment]
I just hope this doesn't break any other fringe case. ;-)
