### ISSUE TITLE
Qt6 support?

### ISSUE THREAD

**Issue by ConiKost** [shundhammer/qdirstat#242]
Are there any plans to support Qt6 in future?

**Comment by ConiKost** [comment]
Thanks for clarifying! :-)

**Comment by shundhammer** [comment]
I don't even know how big the difference between Qt-5.x and Qt-6.x is. Some APIs might have slightly changed, some others some more.

But moving to a new major Qt version will probably cut off some older distros from QDirStat, and I'd like to avoid that for some more time to come. Right now I haven't seen a real benefit yet; but in all honesty, I also haven't looked very thoroughly.

**Comment by ConiKost** [comment]
As for Gentoo, this should not be a problem, we have Qt6 ;-) But I have seen many projects, which just started to support Qt5 and Qt6, so you can just choose during build, which version against you want to compile.

**Comment by Lithopsian** [comment]
I've ported to Qt6 and kept compatibility with Qt5.  Not too hard.  A fair amount of work if you want clean compiles with no deprecation warnings, but they're already turned off by default anyway.  QRegExp -> QRegularExpression is perhaps the most work if you want to go that far.  QTextStream::endl; changing to Qt::endl; caused the most changes.  Couple of other annoying namespace changes and the expected odd glitches that were always there but didn't show up until Qt6 changed something.  Mostly 5.15 is already compatible with 6.

**Comment by ConiKost** [comment]
Maybe you want fill a PR?

**Comment by ConiKost** [comment]
@shundhammer More than a year passed. Could you ellobrate about plans, if qt6 support will come in near future? In Gentoo, we are now on the way to migrate fully to Qt6 and could (which is not yet decided) drop packages, which don't support Qt6 in future. Given the answer by @Lithopsian which did some, this seems doable?

**Comment by Lithopsian** [comment]
A fairly minimal Qt6 pull request was submitted and rejected in issue #194.  As you can see, a basic conversion is relatively easy, depending on how many deprecation warnings you can tolerate.  Or it can be taken much further, and all the deprecations (still happening right up to 6.8) replaced or ifdef'd.

**Comment by a17r** [comment]
> In theory yes, but that would mean a ton of `#ifdef`s everywhere, making the code ugly, awkward and hard to read. I kept it somewhat compatible to Qt-4.x for quite some time since a buddy of mine insists on using an ancient release that doesn't even Qt-5.x support. But if that breaks, that's just a matter of "too bad". ;-)
> 
> Old, but still maintained versions of business Linux can be a problem. SLE-12 SP5 is still out there (and it will probably get an SP6, if that one isn't out yet), and they have absolutely _ancient_ versions of everything but the kernel and some other select components. I don't think they will get Qt-6.x anytime soon, but believe it or not, SLE-12 SPx still has a lot of ~life time~ maintenance years in it...

If that's a concern, surely `stable-1.9` branch is all that you need for supporting old-timers like that, and you can cherry-pick the odd bugfix from git master.
