### ISSUE TITLE
Find files subtree not updated when the DirTree is reloaded

### ISSUE THREAD

**Issue by Lithopsian** [shundhammer/qdirstat#247]
In the find files dialog, the current subtree is set to the current (selected?) subtree in the DirTree.  The first time the dialog is loaded, with a tree, this seems fine.  If a new tree is loaded and find files opened, without making any explicit selection, the subtree still shows with the previous tree.  Executing a search does seem to run against the current DirTree, not the one shown in the dialog.

**Comment by shundhammer** [comment]
It's a bit difficult to reproduce: You have to actively deselect the current selection (the root) after loading a new tree, so I don't think this is a real world problem. I also just verified that it falls back to the root if that last path could not be located in the current tree; so it's really more a cosmetic problem.
