### ISSUE TITLE
Unexpected results when refreshing the locate files window

### ISSUE THREAD

**Issue by Lithopsian** [shundhammer/qdirstat#248]
To reproduce, perform a search that returns a fairly large number of hits.  If it already has more than 1,000, all the better.  Hit refresh.  If you have less than 1,000 hits, you might have to hit refresh several times.

I debugged this one because it seemed so odd at first glance, but in the end it looks like the internal hit counter just isn't getting reset on the refresh.  So it either overflows immediately or once enough refreshes have been done to total up to 1,000.

I guess the counter should be reset in prepare()?

**Comment by shundhammer** [comment]
That sounds plausible. Let me check.

**Comment by shundhammer** [comment]
Actually, it was both, resetting the base class's `_overflow` flag for all other `TreeWalker`s and `_count` for the `FindFilesTreeWalker`.

Good catch!
