### ISSUE TITLE
Accelerator clashes

### ISSUE THREAD

**Issue by Lithopsian** [shundhammer/qdirstat#249]
On the file size statistics window, the Histogram and Help pages both have &H.

On the exclude rules configuration page, Pattern Syntax and Fixed String both use &S.

In the cleanup actions, Move to Trash and Open Terminal  both have &T.  Move to Trash is fixed and Open Terminal is as configured in StdCleanup.  This also clashes with To Toplevel in context menus.

Open File Manager Here and Refresh Selected in the context menu both use &F (or &f).

I think that's everything.  I just went through all the places and combinations I could think of to look for more.

**Comment by shundhammer** [comment]
In the YaST UI engine, I wrote a keyboard shortcut conflict resolver many (20+?)  years ago. Qt never got around to do anything like this; they just move the keyboard focus between several widgets with the same shortcut, which makes the shortcuts pretty pointless.

Sigh.

**Comment by shundhammer** [comment]
"Clean Up" / context menu -> "Open File mana**g**er" is already &G now, but that's read from the cleanup config file which has priority. You probably have a config file from before that change. Check `~/.config/QDirStat/QDirStat-cleanup.conf`. If you delete that file, the defaults will be regenerated.

**Comment by shundhammer** [comment]
https://github.com/libyui/libyui/blob/master/libyui/src/YShortcutManager.h#L65-L105
https://github.com/libyui/libyui/blob/master/libyui/src/YShortcutManager.cc#L63-L160

The caveats are the same here, of course: There are only 26 to choose from (`A`..`Z`), and not all of them occur in the widgets' labels, so in real life it's fewer than that. Any of them that are accessible all over the program make the problem a lot worse. Not all conflicts can be resolved, automatically or manually.

**Comment by Lithopsian** [comment]
My configuration shows the hotkey as ctrl-G, but the accelerator still F (Open &File manager).  Wonder how that happened?

Is the hotkey configurable in the config dialog, or only by hand in the conf file?  I see ctrl-G in the menus but nowhere in the config dialog.

**Comment by shundhammer** [comment]
The `Ctrl`+`G` hotkeys for cleanups are configurable only manually in the config file, the other one (the menu shortcut) is part of the cleanup name that you see in the cleanup config dialog.

**Comment by shundhammer** [comment]
Notice that all changes to cleanups become visible only when removing the cleanup config file `~/.config/QDirStat/QDirStat-cleanup.conf`.

To keep any custom cleanups, copy that file, strip it down to only the custom ones, and change their sections to a larger number, e.g. `[Cleanup_90]`, `[Cleanup_91]` etc., then remove `QDirStat-cleanup.conf`, start and exit QDirStat, and afterwards append the file with the custom cleanups to `QDirStat-cleanup.conf`. The next QDirStat start will fix the numbers of the added custom cleanups.
