### ISSUE TITLE
Fonts can't always be resized in the output window

### ISSUE THREAD

**Issue by Lithopsian** [shundhammer/qdirstat#250]
Do some action that produces an output window.  Zoom out a few times.  Probably only needs to be once or twice.  Then try to zoom back in again, won't happen.  Zoom reset still works.

This is a rounding issue, or lack of rounding issue, with fonts expressed in whole number points.  For example, 8.0 * 1.1 gets truncated back to 8.  Rounding would  help; then the zooming out would stop at 5 (5 / 1.1 would be rounded back to 5).  Arguably 5 points is small enough for anyone, but who knows?  Forcing the zoom to always change by at least a point is perhaps the answer.

The zoom code for fonts expressed in pixels (does that ever happen in this window?) has rounding, although it always starts with an integer, so still has potential problems getting stuck at 5 pixels.

**Comment by shundhammer** [comment]
Yes, I know; that's only after wildly clicking, and then it needs a click on "zoom reset". No harm done.
