### ISSUE TITLE
Cross filesystems setting not respected

### ISSUE THREAD

**Issue by Lithopsian** [shundhammer/qdirstat#252]
The global configuration settings "CrossFilesystems" should control whether the checkbox in the open directory dialog is checked the first time that it is used.  After that, whatever checkbox state was set in the dialog is kept the next time the dialog is opened, until that program run ends.  Then the next time it runs, the setting from the configuration file is read again.  The setting in the conf file is not changed based on what is chosen in the dialog, but can be changed from the config dialog (but won't affect the open directory dialog until the program is restarted).

This doesn't happen.  The box is never checked the first time the dialog is opened.  The static flag in OpenDirDialog is initialised to false, used to set the checkbox, and then readSettings() is called to get the value from the conf file.  The static flag now has the value from the conf file, but too late to affect the dialog.  If the dialog is cancelled, the value from the conf file will then be applied to the checkbox the next time the dialog opens.  If the dialog is accepted, then the flag will be overwritten with whatever state the checkbox was in.

**Comment by shundhammer** [comment]
The global flag does work, but only for URLs passed on the command line, not if using the `OpenDirDialog`. That is obviously wrong; the global flag should indeed initialize the checkbox in that dialog.

**Comment by shundhammer** [comment]
The code was there, but called slightly too late.
