### ISSUE TITLE
Crash when unable to open a cache file

### ISSUE THREAD

**Issue by Lithopsian** [shundhammer/qdirstat#255]
If the open of a cache file fails (eg. no read permission or a typo on the command line), then the program crashes immediately at line 269 in DirTreeCache.cpp.

It appears that a CacheReadJob is created with a null CacheReader because the CacheReadJob detects the failed open and destroys the reader.  However, DirTree::readCache() doesn't check this and adds it to the job queue (DirTree.cpp:451).  When the job is de-queued, it detects that the reader is null (DirReadJob.cpp:700), emits a finished() signal (the wrong signal?), and then attempts to read it anyway, which causes a segmentation fault.

Probably the job should never be added to the queue.  Possibly an aborted() signal should be emitted?  Otherwise the main window timer will just keep going.  Just as a double-check, the CacheReadJob should abort if it detects a null reader, and not try to use it.  Emitting finished() probably isn't a good idea.  The reader itself emits error() signals, but I don't think anyone is listening.

Or maybe keep it simple and return an error code directly since the failure is synchronous.  Not sure exactly what the main window should do if that happened though.  Perhaps just call the readingAborted() slot directly.  I don't know if the error merits anything more informative for the user, but easy enough to throw a different progress message in the status bar.

**Comment by shundhammer** [comment]
Duh. A lot of error checking - and then forgetting to return.

**Comment by shundhammer** [comment]
But you are right, it isn't nice not to notify the user that this didn't work.

It might still be somewhat acceptable if afterwards the tree is completely empty, so the user should be aware that something is wrong; but if a cache file was picked up while traversing a directory tree, and it couldn't be read, that would go completely unnoticed.

**Comment by shundhammer** [comment]
Now at least handling the common case better: A cache file passed on the command line or selected via menu that cannot be read.

This still leaves the case when a cache file is picked up while scanning the tree, but that is logged, and as a fallback the directory will be read directly if the cache file cannot be read. And it's a very uncommon case, too.

It would also be disruptive to open an error pop-up in that case while reading; a panel message would be much more appropriate. But that would have to go over many layers of classes and methods all the way from a `DirReadJob` up to the `MainWindow`; it would add a lot of complexity to the code for little gain.

**Comment by Lithopsian** [comment]
The case of automatically picking up a cache file during a read throws up a few other oddities too.  Obviously, there is no indication that the displayed tree may not match reality, but also there are no permissions in the cache file.  That prevents identification of executable files, and shows strange permissions data in the tree and file details panel.  Handy for experts, confusing for most people.

**Comment by shundhammer** [comment]
I am not sure if anybody actually uses that. Yes, it comes with limitations.

The idea was to support large archive volumes that are changed only very rarely; the limitations are probably acceptable for that use case. Of course times have changed since this feature appeared; it was long before there was the "Details" panel.

But it's there, and there is the off chance that some users find it useful, limitations or not.
