### ISSUE TITLE
Package member file sometimes not showing package data in file details view

### ISSUE THREAD

**Issue by Lithopsian** [shundhammer/qdirstat#258]
1. Make the file details panel visible.
2. Open a non-system directory and select a file (this hides the package info block).
3. Open a package view and select a file.

In the file details view, the package block is still hidden, although the fields in it have actually been set correctly.
![Screenshot_2024-02-01_19-45-59](https://github.com/shundhammer/qdirstat/assets/7702742/d47f5c84-8fbc-4d6e-abc8-6c787eaf564a)

FileDetailsView only sets the visibility of the package caption and label for files that don't have a package ancestor.  For files in packages, the label is enabled and the package is hard-coded from the parent, but the visibility is not changed.  So if it was hidden before, it stays hidden.  The caption is also not enabled, so it it was not enabled before, it stays not enabled even though there is a package.
![Screenshot_2024-02-01_19-52-19](https://github.com/shundhammer/qdirstat/assets/7702742/7ff7ae07-2360-4619-b15f-8b514cffe222)

**Comment by Lithopsian** [comment]
Also, packages are counted as "files" in the selection summary:
![Screenshot_2024-02-01_20-21-58](https://github.com/shundhammer/qdirstat/assets/7702742/fc8f305a-b9d1-4f85-8ed1-eebea431d284)
They might be better coming under the directory heading.  Changing isDir() to isDirInfo() on line 595 would do it.

**Comment by shundhammer** [comment]
Provisions for showing the owning package in the pkg view were already in place, but managing the visibility of the pkg info block didn't work. It was probably coincidence that when creating the details panel, the block was enabled by default; so only switching between a normal tree view and the pkg view triggered the problem, and then only if just prior to loading the pkg view a non-system file was selected.
