### ISSUE TITLE
Sorting arrows used incorrectly 

### ISSUE THREAD

**Issue by hauau** [shundhammer/qdirstat#26]
Wide side of sorting arrow should depict bigger values and vice versa.
Currently (V1.0 2016-08-12): 
![Incorrect orientation](http://i.imgur.com/ExDv9FV.png)

**Comment by shundhammer** [comment]
No. The down arrow (v) means "ascending" sort order, i.e. A-Z or 0-9, the up arrow (^) means "descending", i.e. Z-A or 9-0. That's how Qt does it (which is the underlying toolkit that QDirStat uses).

I was a bit surprised that this seems to be a topic of heated debate, for example here:

http://ux.stackexchange.com/questions/37564/use-up-or-down-arrow-to-represent-sort-ascending-at-table-header

I was also surprised to hear that this appears to be different from toolkit to toolkit or from platform to platform.

Yet, QDirStat will use the standard behaviour of its underlying toolkit. And it makes sense, too: Arrow down (v) meaning "downward order", i.e. sorted from top to bottom, A-Z, 0-9; arrow up meaning "upward order", Z-A, 9-0.

I will leave the pointless philosophical discussions to the UX people who can debate about such things until kingdom come without any useful result whatsoever (been there, had to suffer from it countless times).

**Comment by shundhammer** [comment]
BTW for a simple example, try a Qt file selection box and check how it behaves.
