### ISSUE TITLE
question for use in linux with huge links

### ISSUE THREAD

**Issue by Maziar123** [shundhammer/qdirstat#260]
I need Linux GUI to get a similar baobab with one crucial feature: don't sum the size of the hard link or soft link file because I need to calculate disk usage of the backup tree with huge links, then baobab or similar to get fault results
 if I can not get actual disk usage of the folder tree, it is not usable for me

Can we set for doing with **qdirstat**?

**Comment by shundhammer** [comment]
I am not sure what you mean with "huge links". If you mean not summing up files with multiple hard links with their proportion, i.e. _total_size_ / _number_of_links_, that would be this:

https://github.com/shundhammer/qdirstat/issues/124#issuecomment-595811687

Released with QDirStat 1.7 and documented here:

https://github.com/shundhammer/qdirstat/releases/tag/1.7

> **Completely Ignore Hard Links**
>
> Added a config option to ignore hard links.
>
> This is useful for a very small number of use cases. Hard links are not very common anymore in today's Linux / BSD / Unix-like systems, so most users won't have to bother with this at all.
>
> By default, QDirStat sums up the disk space for a file with multiple hard links for each hard link's share of the overall size: If a file with 1 MB has 4 hard links, for each of those 4 links QDirStat adds 1/4 of the size (i.e., 256 kB) to the parent directory. If all those 4 links are in the same directory, that's very simple: They add up to 4 * 256 kB = 1 MB, so the sum is correct.
>
> If those hard links are all in different directories, each directory only gets part of that disk space allocated, because in fact they share the disk space among each other; the total disk space sum taking all those directories into account is still correct, of course.
>
>The trouble starts when you want to make a backup of only one of those directories: Even though the disk space is still shared with other directories, on the backup medium, you still need the disk space for that complete file, i.e. the full 1 MB, not only that directory's share (256 kB). With a lot of hard-linked files, that can add up to a lot of difference between what QDirStat displays and what disk space you actually need for the backup.
>
> ...
> ...

The caveats are hard links inside and outside the subtree that you want to include in your backup.

If they are all outside, then it's no problem: Each file should be accounted for once with the whole size. If some are inside, this will get you a larger sum that the backup will actually need.

I don't know how Baobab handles this; I doubt that it has any smart handling of hard links at all.

**Comment by Maziar123** [comment]
Yes

Exactly me need is IgnoreHardLinks
also, can think about additional columns can very nice !  withlinks & withoutlinks & linkpresent%
