### ISSUE TITLE
qdirstat-cache-writer does not operate correctly with relative paths

### ISSUE THREAD

**Issue by mljatgithub** [shundhammer/qdirstat#261]
This is because in perl chdir does not update $ENV{PWD}. (see: https://github.com/Perl/perl5/issues/18724).

Instead use 'Use Cwd;' and replace:

    $dir = $ENV{'PWD'};

with     $dir = cwd();
or $dir = getcwd();

(Depending on how you wish to behave on paths which have followed symlinks).

Thanks,
Martin.

**Comment by mljatgithub** [comment]
I should clarify - this report is for the qdirstat-cache-writer perl script.

**Comment by shundhammer** [comment]
Thanks!

What I really needed here was `Cwd::abs_path()`; that convoluted way to save the current directory, change to the other one, get its path and then restore the old current directory was just a very pedestrian way to achieve that.

This `qdirstat-cache-writer` code is very old (2003 or so?). I don't remember if back then `Cwd::abs_path()` was readily available in Perl, or if I just didn't know about its existence. Anyway, it's much cleaner now.

I just hope this doesn't open yet another avenue of introducing dependencies. It looks like `Cwd` comes with the standard Perl distribution, not needing another Perl package.
