### ISSUE TITLE
Crash when selecting the dot entry of an aborted package read

### ISSUE THREAD

**Issue by Lithopsian** [shundhammer/qdirstat#264]
1. Start a read of all packages, but really anything long enough to abort should work.
2. Abort the read.
3. Open up one of the aborted packages.  They don't show an aborted icon, but you can tell which they are from all the questions marks.
4. It probably has an empty-looking <Files> child.  Click on that.

Here's a screenshot of the crash, hopefully enough to track down the problem.  Looks like the new PkgInfo objects don't have a dot entry when they're first created, but some code down the line assumes that they do.
![Screenshot_2024-02-22_21-25-55](https://github.com/shundhammer/qdirstat/assets/7702742/6a8c9b40-77b0-4ef9-9875-580093bc49df)

**Comment by shundhammer** [comment]
Aborting can lead to all kinds of problems. I am not going to spend all my weekends debugging crazy scenarios.
