### ISSUE TITLE
QDirStat takes a long time (> 1 min) to start up due to mountinfo processing with 5000 mounts

### ISSUE THREAD

**Issue by Bgamsa** [shundhammer/qdirstat#274]
Using version 1.8 of qdirstat on SUSE 15, it can take a minute or more for it to start on some systems; it opens with just an outline (with the window contents just being whatever was on the screen at that location at the time) and stays that way for a while.  stracing it seems to suggest that it is spending most of the time processing /proc/self/mountinfo.  The machine I'm testing on has over 5000 mount entries, and from the strace it seems like qdirstat is processing the entire file once for every entry in the file.  Even if I give it an explicit path to process from the command line, it still processes all of the mountinfo entries.

**Comment by shundhammer** [comment]
Yes, QDirStat does read `/proc/mounts` - for a variety of reasons, starting with being able to determine whether or not a directory that is being read is on a different block device or still on the same one as its parent. Some filesystem types like Btrfs misbehave in any number of ways to make life harder for users; Btrfs subvolumes come to mind.

I don't see a way to prevent that without sacrificing features to support much more common scenarios. But really, reading 5000 lines from a pseudo filesystem like `/proc/mounts` (which is actually just a kernel table); how long can that actually take on today's hardware?

**Comment by shundhammer** [comment]
With a normal setup, the time for reading the mount points isn't even really measurable:

```
12:55:29.954 <Info>    DirTree.cpp:141 startReading():     url: "/work/home/sh/src/qdirstat"
12:55:29.954 <Debug>   SysUtil.cpp:103 runCommand():  /bin/lsblk --noheading --list --output name,fstype
12:55:29.960 <Debug>   MountPoints.cpp:552 findNtfsDevices():  No NTFS devices found
12:55:29.960 <Debug>   MountPoints.cpp:357 read():  Reading /proc/mounts
12:55:29.961 <Debug>   MountPoints.cpp:414 read():  Read 37 mount points from /proc/mounts
```

```console
% lsblk -o NAME,SIZE,FSTYPE,LABEL,MOUNTPOINTS

NAME          SIZE FSTYPE      LABEL    MOUNTPOINTS

nvme0n1     953.9G                      
├─nvme0n1p1   512M vfat        efi-boot /boot/efi
├─nvme0n1p2     2G swap        swap     [SWAP]
├─nvme0n1p3   100G ext4        root-01  /
├─nvme0n1p4   100G ext4        root-02  /alternate-root
├─nvme0n1p5   200G crypto_LUKS          
└─nvme0n1p6 551.4G ext4        work     /work

% inxi

CPU: 12-core (2-mt/10-st) Intel Core Ultra 5 125U (-MST AMCP-)
speed/min/max: 1187/400/4300:3600:2100 MHz Kernel: 6.11.2-1-default x86_64
Up: 4d 15h 4m Mem: 2.38/15.12 GiB (15.7%) Storage: 953.87 GiB (12.5% used)
Procs: 327 Shell: Zsh inxi: 3.3.36
```

I also checked if any external commands are called for each mount poin, but not; but it's really just that single `lsblk` call (just once, not for each mount point) to check if there are any NTFS mounts.

Please try

```console
% time wc -l /proc/mounts

37 /proc/mounts
wc -l /proc/mounts  0.00s user 0.00s system 84% cpu 0.002 total

% time /bin/lsblk --noheading --list --output name,fstype

nvme0n1   
nvme0n1p1 vfat
nvme0n1p2 swap
nvme0n1p3 ext4
nvme0n1p4 ext4
nvme0n1p5 crypto_LUKS
nvme0n1p6 ext4
/bin/lsblk --noheading --list --output name,fstype  0.00s user 0.01s system 92% cpu 0.006 total
```

**Comment by shundhammer** [comment]
I generated a mockup `/proc/mounts` with this bash command:

```console
% for i in $(seq 1 5000) ; do printf "/dev/fake%04d  /mounts/fake%04d  ext4  defaults  0  0\n" $i $i ; done

/dev/fake0001  /mounts/fake0001  ext4  defaults  0  0
/dev/fake0002  /mounts/fake0002  ext4  defaults  0  0
/dev/fake0003  /mounts/fake0003  ext4  defaults  0  0
...
...
/dev/fake4998  /mounts/fake4998  ext4  defaults  0  0
/dev/fake4999  /mounts/fake4999  ext4  defaults  0  0
/dev/fake5000  /mounts/fake5000  ext4  defaults  0  0
```

...and added the real `/proc/mounts` content to its end:

```
cat /proc/mounts >>fake-mounts
```

...and hacked up `MountPoints.cc` to read that file instead.
```
13:23:31.843 <Info>    DirTree.cpp:141 startReading():     url: "/work/home/sh/src/qdirstat"
13:23:31.843 <Debug>   SysUtil.cpp:103 runCommand():  /bin/lsblk --noheading --list --output name,fstype
13:23:31.849 <Debug>   MountPoints.cpp:552 findNtfsDevices():  No NTFS devices found

13:23:31.849 <Debug>   MountPoints.cpp:357 read():  Reading ./fake-mounts
13:23:32.014 <Debug>   MountPoints.cpp:414 read():  Read 5037 mount points from ./fake-mounts

13:23:32.014 <Info>    DirTree.cpp:144 startReading():  device: /dev/nvme0n1p6

13:23:32.060 <Info>    MainWindow.cpp:521 readingFinished()
```

So reading 5037 mount points takes a whopping 154 milliseconds on a moderate laptop.

**Comment by shundhammer** [comment]
So please check with the commands above if maybe it's the kernel on your hardware that causes that delay; maybe it doesn't scale in a linear way with the number of mount points. But that would be a bug report against the kernel, not against QDirStat.

Having said that, 5000 mount points sounds very excessive to me. Is that on an s/390 mainframe where we (the YaST team) were always told that we could expect hundreds of DASDs? If so, I was always under the impression that those architectures were meant to be optimized for I/O bandwidth, not so much for number crunching.

**Comment by Bgamsa** [comment]
Thanks for investigating.  I checked the time just to read the file, and it's about 25ms (which is still a lot for 5000 entries, but I'm not sure what the kernel is doing behind the scenes).  However, the problem is not that it needs to read a 5000 entry virtual file, it's that it reads it once, in it's entirety, for every entry in the file.  That is, there are 5487 entries in /proc/self/mountinfo, and when I strace qdirstat, I see 5487 openat("/proc/self/mountinfo") calls.

As for why there are so many entries, I was a little surprised myself.  It's a regular Linux system, but it seems like instead of using automount it has all of the potential remote filesystems already mounted.  I'm assuming, though, that if we can get rid of the N^2 behaviour, then that shouldn't be a problem.

**Comment by shundhammer** [comment]
Gotcha: QDirStat 1.8 created a `QStorageInfo` unconditionally for every mount point immediately, and that caused an `fstatfs()` syscall for that filesystem.

That was one of the major changes between 1.8 and 1.8.1, but for a different reason: It could cause hanging because of temporarily inaccessible network mounts (Samba, NFS), even they were clearly not used because you specified a different path on the command line.

Obtaining that information for every single one of your 5000 mounts might have a similar effect, but more likely because of kernel buffer thrashing when it needs to page in all those mount table entries.

The fix is easy: Update to the latest stable QDirStat 1.9. 

If you can't do it on that machine because of insufficient permissions, build your own from source.

**Comment by Bgamsa** [comment]
Great, thanks.
