### ISSUE TITLE
Display tooltips for files upon hovering

### ISSUE THREAD

**Issue by Smile4ever** [shundhammer/qdirstat#28]
It would be nice to see the file name and size if you hover above a file in the colored view.

**Comment by shundhammer** [comment]
Tooltips in the treemap have a nasty habit of getting in the way (like tooltips very often do). That information is just one single mouse click away if you really want it: When you click on a tile in the treemap, the corresponding item is shown in the tree view. In addition to that, the full path name and the size are also shown in the status bar at the bottom of the window.

**Comment by shundhammer** [comment]
The moment such tooltips are there, somebody else will (understandably) want a configuration option to disable them to be free to move the mouse cursor in the treemap without the tooltip obstructing what he wants to point to. In general, tooltips are mostly a PITA and useful only for things like toolbar buttons that only have small icons that are frequently not self-explanatory enough to make sense of what the button does.
