### ISSUE TITLE
Double click a file to open it in the default application

### ISSUE THREAD

**Issue by Smile4ever** [shundhammer/qdirstat#29]
I expect QDirStat to open files with the default application (using xdg-open) when I double click them in the tree view.

**Comment by shundhammer** [comment]
You can easily configure that as a cleanup action, even with a keyboard shortcut (if you are willing to edit the config file - see other cleanup actions for examples how to specify keyboard shortcuts).

But not only is QDirStat not a general-purpose file manager (where people really do expect such behaviour), it would also be inconsistent behaviour between the tree view and the treemap: The treemap zooms in with a double click; doing something completely different in the tree view would be confusing. One can argue that double-clicking a directory in the tree view (which opens the corresponding branch) is something similar to zooming in (more exactly, refining the view to show something more detailed).

**Comment by shundhammer** [comment]
Verdict: Not desired. There is no resolution among the GitHub labels that really corresponds to that.

**Comment by Smile4ever** [comment]
Thanks for highlighting the cleanup actions, it's a nice workaround.
