### ISSUE TITLE
openSUSE package for qdirstat

### ISSUE THREAD

**Issue by dmacvicar** [shundhammer/qdirstat#3]
You can find it in https://build.opensuse.org/package/show/home:dmacvicar/qdirstat

Some notes:

* Because lack of tarballs and tags, I used a OBS `_service` file to generate the tarball and update the version in the spec. So the package sources will be re-fetched from git every time the package is rebuilt.

* You can automate that github commits trigger a `_service` rebuild of the sources (tarball and spec version update). It is described [here](http://openbuildservice.org/2013/11/22/Source-Update-Via_Token/).

* The version format is 0.8+git.1452544836.ea0d400 where the first number is a timestamp and then the git hash. The `0.8 is for now hardcoded in `_service` and taken from an internal constant.

* Ideally `0.8` should be replaced with `@PARENT_TAG@` in `_service`, then OBS would look for the parent tag (eg. `0.9`) in git of the branch we are building (by default, master) and then automatically generate `0.9+git.$s.$rev`.

* As a first step I would recommend just start tagging releases  with plain version numbers (eg. no `v`), and keep building from master. Later you can switch `_service` to build from stable branches if needed.

* If you dislike the server side magic to generate the tarball and update the spec, there is an alternative method where you can update the tarball to the latest git revision manually in your checkout:

  * Add an attribute `mode="disabled"` to the `service` elements in _service.
  * Run `osc service disabledrun` to update the tarball and .spec file version
  * You will need in this case, to checkin the generated tarball, as it will not longer be autogenerated.

* Feel free to `osc copypac` this package to somewhere else.

**Comment by shundhammer** [comment]
OK, thank you!

**Comment by shundhammer** [comment]
Packages now available. See README.md.

Thanks again, Duncan!

**Comment by dmacvicar** [comment]
You are welcome.

BTW, you can also use this single url to link to the packages (it is more user friendly):

https://software.opensuse.org/download/package?project=home:shundhammer&package=qdirstat
