### ISSUE TITLE
How do u download

### ISSUE THREAD

**Issue by fesararwa** [shundhammer/qdirstat#42]
I cant figure out how to download someone tell me pls

**Comment by fesararwa** [comment]
I just switched from windows and i need WinDirstat and this seemd good but i need to install it somehow

**Comment by shundhammer** [comment]
RTFM

**Comment by shundhammer** [comment]
You mean you managed to figure out how to use this issue tracker, but you couldn't be bothered to read the home page (README.md) where both building this program from source (for more advanced users) and using ready-made binary packages (RPMs for SUSE, .deb for Ubuntu/Debian) is explained in great detail?

You seriously want me to give you total beginner's lessons how to do basic things in Linux -- via a bug tracker, of all things?

Get real. RTFM. Get a book. Read online articles and tutorials. Get informed. Whatever - don't waste other people's time before you even started investing just a little bit of your own.

Open Soure is not about getting cool stuff for no money -- it is about participating, about being part of the community. And that includes some respect of other people's time and work and not just sitting on your ass, waiting for others to do the work for you.

**Comment by laurent22** [comment]
To be fair, RTFM is not such a great option because the readme file is about 22 pages and the way to install it via apt-get is just one line in this long wall of text. Searching for "deb", "install" or "apt" brings nothing. Now I see that "ppa" was the keyword.

Perhaps the "Install" section should be completely at the top, since this is what most users want to do?

**Comment by shundhammer** [comment]
If people can't be bothered to read more than the topmost lines, frankly they just don't deserve to use other people's work for free. I spent a lot of my time writing this documentation; I don't think it is asking too much for people to read at least the essential parts of it to make use of the program.

I've been doing this for 30+ years now, and people keep complaining about missing documentation while at the same time complaining again when it takes more than 15 seconds (the typical attention span of today's hyperactive kids) to read it completely...

**Comment by shundhammer** [comment]
Searching the page for "download" (which is what the original poster asked for) gives 4 results where the second one is smack in the middle of the relevant section of the documentation.
