### ISSUE TITLE
Compilation error for Qt4

### ISSUE THREAD

**Issue by dufgrinder** [shundhammer/qdirstat#46]
Hi,

Nice tool.

I've encountered a compilation error on Fedora 25 for QDirStat v1.2 with qt-devel-4.8.7-18.fc23.x86_64

File Logger.cpp, Line 287 should b aware of Qt version 

#if (QT_VERSION < QT_VERSION_CHECK( 5, 0, 0 ))
        if ( !strstr(msg, "Could not connect to display" ) )
#else
        if ( msg.contains( "Could not connect to display" ) )
#endif

And then it works fine,

KR, Olivier

**Comment by shundhammer** [comment]
Should be fixed in git already.
