### ISSUE TITLE
Locate files by type from the File Type Statistics window

### ISSUE THREAD

**Issue by shundhammer** [shundhammer/qdirstat#48]
# Idea

The new _File Type Statistics_ window presents files by type: Category (Images, Videos, Documents, ...) in the top level, individual suffixes (filename extensions) in the next level.

![qdirstat-file-type-stats](https://cloud.githubusercontent.com/assets/11538225/23074250/9df1208a-f538-11e6-97af-7cdef4a2578e.png)

It would be useful to be able to locate files with a chosen suffix from there:

- Click on one of the suffixes in the _File Type Statistics_ window; say, *.bak

- Open another (non-modal) window for the search results; probably one entry per directory that contains any files with that suffix.

- When clicking on one of those search results, open that directory branch in the main window (similar to clicking on a treemap tile) while closing all other branches

- Select (highlight) all matching files in that directory (they will automatically be highlighted in the treemap,too)

- The user can now start cleanup actions for those files in the main window.

# Limitations / Unsolved Problems

That will work well with a handful of files; It is still unclear how to do this efficiently with things like my photo collection: It's 29,000+ JPG files scattered over 850+ directories. That's a bit much to navigate in. Would I want only my /work/photos directory to appear there? That's a bit limiting. 

This is subject for further investigation and discussion.

**Comment by C0rn3j** [comment]
Just a small thing - F3 currently only opens the file stats window, how about having it toggle it instead?

**Comment by flurbius** [comment]
Maybe select just the directories rather than the files.

Or a better solution might be to only select the files within directories that are selected in the search results window. 

The user story would go 
1. open the File type stats window.
2. select a File type (and click search)
3. search results are presented - each result is a directory that contains some of that file type, along with the number of files, number of files of that type and the combined space taken up - total and percent.
4. the user selects one or more search results, and the files that are represented in the results are selected


That way it is up to the user how many files they will try to select,

**Comment by shundhammer** [comment]
![qdirstat-locating-file-types](https://cloud.githubusercontent.com/assets/11538225/23139114/28de4230-f7ab-11e6-9914-5710406829dc.png)

All three windows work in concert:

- You select a file type (a filename extension) in the "File Type Statistics" window.

- You click "Locate" or you double-click the item.

- The "Locate Files" window opens.

- You click a directory there.

- In the main window, the branch for that directory opens, and all matching
  files are selected in the tree view and in the treemap.

- You can now directly start cleanup actions for those files.

**Comment by shundhammer** [comment]
The results window is reused as long as it remains open. You can even close the _File Type Statistics_ window when it gets in the way; when you open it again (with F3 or menu "View" -> "File Type Statistics"), the same results window is used.

**Comment by shundhammer** [comment]
Initially I was afraid that it would become very slow with many directories, but that fear was unfounded: There is no problem selecting "*.jpg" which means there will be some 900 directories in the results window. It takes two or three seconds, but there is no problem.

**Comment by shundhammer** [comment]
Correction: it's not 2-3 seconds, it's ~200 millisec:

    2017-02-20 21:00:21.106 [18147] <Debug>   LocateFilesWindow.cpp:104 locate():  Locating all files ending with ".jpg"
    2017-02-20 21:00:21.314 [18147] <Debug>   LocateFilesWindow.cpp:114 locate():  920 directories
