### ISSUE TITLE
"Open in File Manager" has confusing effects for a file

### ISSUE THREAD

**Issue by cornelius** [shundhammer/qdirstat#5]
When using the "Open in File Manager" action on a file, it can have a somehow confusing effect. Usually no file manager is opened, but an editor, or some other application. Sometimes also nothing happens.

Maybe this could be more like an "Open with..." action with xdg-open as default or something like that.

**Comment by shundhammer** [comment]
Yes, this is a similar issue as with the xterm/konsole/... problem: xdg-open is too generic. It should start the correct file manager, depending on the current desktop.

**Comment by shundhammer** [comment]
Changed name and semantics to "open file manager here" with the new %filemanager macro which is different for each desktop. See README.md from today (2016-01-15).

**Comment by shundhammer** [comment]
P.S. You will probably have to delete the config file to make that work, otherwise you won't get the new defaults:

rm ~/.config/QDirStat/QDirStat.conf

**Comment by cornelius** [comment]
Works nicely now. :+1:
