### ISSUE TITLE
Log file world-readable with umask 022 and in fixed /tmp location

### ISSUE THREAD

**Issue by PhobosK** [shundhammer/qdirstat#50]
Actually there are 2 problems with the log file... I will start with the security one...

**Problem 1:** Being written in /tmp , the log file is readable by anyone since in this folder when creating files their permissions usually are set to 644... A small change in src/Logger.cpp constructor is needed... Adding some **_QFile::setPermissions_** would help great to limit the reading at least to user and group, so no user sensitive info from the log leaks...

**Problem 2:** The log file location is hardcoded to /tmp... This better be coded using either **_QStandardPaths::TempLocation_** or some of the env variables like _TMPDIR_ on Linux, or _TEMP_ on Windows....

**Comment by shundhammer** [comment]
And what confidential information did you find in that file?

**Comment by shundhammer** [comment]
As for the log's permissions: The user's _umask_ is of course applied. So as with all files the user creates, it is his choice how restrictive he wants to handle that.

**Comment by shundhammer** [comment]
Obviously it is perfectly acceptable to have log files world readable:

    kubuntu-14.04-box % find /var/log -perm +004 -ls
    146026    4 drwxrwxr-x  13 root     syslog       4096 Feb 18 15:20 /var/log
    131469    8 -rw-r--r--   1 root     root         7987 Nov  4 14:29 /var/log/dpkg.log.4.gz
    262956    4 drwxrwxr-x   2 root     root         4096 Jan 18  2015 /var/log/installer
    262962    4 -rw-r--r--   1 root     root           62 Jan 18  2015 /var/log/installer/media-info
    262964  424 -rw-rw-r--   1 root     root       433881 Jan 18  2015 /var/log/installer/initial-status.gz
    131853   16 -rw-r--r--   1 root     root        13109 Feb 19 01:43 /var/log/battery-stats
    153810    4 drwxr-xr-x   2 root     root         4096 Sep  4 22:24 /var/log/ConsoleKit
    132309    4 -rw-r--r--   1 root     root          313 Apr 15  2016 /var/log/ConsoleKit/history.5.gz
    134027    4 -rw-r--r--   1 root     root          303 Apr 29  2016 /var/log/ConsoleKit/history.4.gz
    131948    4 -rw-r--r--   1 root     root          663 Sep  4 22:24 /var/log/ConsoleKit/history.1.gz
    131090    8 -rw-r--r--   1 root     root         6056 Jul 27  2016 /var/log/ConsoleKit/history.1
    131247    4 -rw-r--r--   1 root     root          121 Feb 26  2016 /var/log/ConsoleKit/history.6.gz
    132186    4 -rw-r--r--   1 root     root          643 Jun 26  2016 /var/log/ConsoleKit/history.2.gz
    131768    4 -rw-r--r--   1 root     root          449 Mai 26  2016 /var/log/ConsoleKit/history.3.gz
    131154   44 -rw-r--r--   1 root     root        37102 Feb 18 13:49 /var/log/ConsoleKit/history
    132084    4 -rw-r--r--   1 root     root         1296 Dez 22 21:07 /var/log/alternatives.log.3.gz
    153812    4 drwxr-xr-x   2 root     root         4096 Feb 16 21:51 /var/log/cups
    132203    4 -rw-r--r--   1 root     root         1609 Dez 23 17:02 /var/log/pm-powersave.log.3.gz
    131729    8 -rw-r--r--   1 root     root         4900 Jan 19 23:27 /var/log/pm-suspend.log.2.gz
    132064    4 -rw-r--r--   1 root     root          365 Mai 25  2016 /var/log/alternatives.log.9.gz
    131855   20 -rw-r--r--   1 root     root        16529 Feb  2 21:29 /var/log/pm-suspend.log.1
    131218    4 -rw-r--r--   1 root     root          442 Jan 19 23:33 /var/log/alternatives.log.1
    132482    4 -rw-r--r--   1 root     root          368 Sep 22 23:38 /var/log/alternatives.log.5.gz
    131918   12 -rw-r--r--   1 root     root         8403 Mai 26  2016 /var/log/dpkg.log.9.gz
    131856   24 -rw-r--r--   1 root     root        19807 Feb 16 21:44 /var/log/battery-stats.1
    153819   12 drwxr-xr-x   2 root     root        12288 Feb 18 13:49 /var/log/upstart
    132143    4 -rw-r--r--   1 root     root          473 Mär 11  2016 /var/log/alternatives.log.12.gz
    131875    4 -rw-r--r--   1 root     root          326 Jul 23  2016 /var/log/alternatives.log.7.gz
    131936    8 -rw-r--r--   1 root     root         6117 Nov  5 13:52 /var/log/pm-suspend.log.4.gz
    131467   80 -rw-r--r--   1 root     root        74690 Feb 19 00:37 /var/log/pm-suspend.log
    131590   20 -rw-r--r--   1 root     root        18903 Mär 27  2016 /var/log/dpkg.log.11.gz
    131486    8 -rw-r--r--   1 root     root         6696 Jul 27  2016 /var/log/dpkg.log.7.gz
    132898    4 -rw-r--r--   1 root     root         2028 Nov  5 13:52 /var/log/pm-powersave.log.4.gz
    131213    8 -rw-r--r--   1 root     root         5683 Apr 28  2016 /var/log/dpkg.log.10.gz
    131675    8 -rw-r--r--   1 root     root         5833 Sep  2 22:27 /var/log/dpkg.log.6.gz
    131478   12 -rw-r--r--   1 root     root        11020 Feb  2 21:29 /var/log/pm-powersave.log.1
    131110   24 -rw-r--r--   1 root     root        24278 Feb 18 15:20 /var/log/Xorg.0.log.old
    131538   12 -rw-rw-r--   1 root     utmp         9984 Feb  2 21:30 /var/log/wtmp.1
    148406    4 -rw-r--r--   1 root     root         2151 Feb 18 13:49 /var/log/gpu-manager.log
    132658    4 -rw-r--r--   1 root     root          532 Okt 31 12:50 /var/log/alternatives.log.4.gz
    132177    8 -rw-r--r--   1 root     root         5078 Dez 23 17:02 /var/log/pm-suspend.log.3.gz
    131359   28 -rw-r--r--   1 root     root        20749 Jan 13 00:02 /var/log/battery-stats.5
    132321    4 -rw-r--r--   1 root     root          925 Mär 27  2016 /var/log/alternatives.log.11.gz
    132576    4 -rw-r--r--   1 root     root          289 Aug 18  2016 /var/log/alternatives.log.6.gz
    131209    8 -rw-r--r--   1 root     root         6176 Okt  3 13:18 /var/log/dpkg.log.5.gz
    133133    4 -rw-r--r--   1 root     root           30 Jan 25  2015 /var/log/prime-supported.log
    131214   24 -rw-r--r--   1 root     root        23449 Feb 18 15:21 /var/log/Xorg.0.log
    131465    4 -rw-r--r--   1 root     root         2730 Feb  5 01:00 /var/log/battery-stats.2
    153811    4 drwxr-xr-x   2 root     root         4096 Feb 16 21:51 /var/log/apt
    132928    4 -rw-r--r--   1 root     root          631 Jan 19 23:32 /var/log/apt/history.log.2.gz
    131546    0 -rw-r--r--   1 root     root            0 Feb 16 21:51 /var/log/apt/history.log
    132110    4 -rw-r--r--   1 root     root         1386 Jul 27  2016 /var/log/apt/history.log.7.gz
    132301    4 -rw-r--r--   1 root     root         1161 Apr 28  2016 /var/log/apt/history.log.10.gz
    132460    4 -rw-r--r--   1 root     root         2145 Dez 22 21:10 /var/log/apt/history.log.3.gz
    131527    4 -rw-r--r--   1 root     root         1567 Mai 26  2016 /var/log/apt/history.log.9.gz
    132071    4 -rw-r--r--   1 root     root          126 Feb 10 00:51 /var/log/apt/history.log.1.gz
    131345    4 -rw-r--r--   1 root     root         1165 Sep  2 22:27 /var/log/apt/history.log.6.gz
    131825    4 -rw-r--r--   1 root     root         1746 Nov  4 14:29 /var/log/apt/history.log.4.gz
    131407    4 -rw-r--r--   1 root     root         1363 Okt  3 13:18 /var/log/apt/history.log.5.gz
    137486    4 -rw-r--r--   1 root     root         1992 Mär 11  2016 /var/log/apt/history.log.12.gz
    131949    4 -rw-r--r--   1 root     root          831 Jun 23  2016 /var/log/apt/history.log.8.gz
    131245    4 -rw-r--r--   1 root     root         4092 Mär 27  2016 /var/log/apt/history.log.11.gz
    131113  312 -rw-r--r--   1 root     root       316382 Feb 18 13:49 /var/log/udev
    153825    8 -rw-r--r--   1 root     root        32032 Jan 30  2015 /var/log/faillog
    153821   64 -rw-r--r--   1 root     root        61499 Jul 23  2014 /var/log/bootstrap.log
    131941    4 -rw-r--r--   1 root     root          663 Jan 19 23:33 /var/log/dpkg.log.1
    132239    4 -rw-r--r--   1 root     root          579 Jun 23  2016 /var/log/alternatives.log.8.gz
    131101    8 -rw-r--r--   1 root     root         4895 Feb 18 13:49 /var/log/boot.log
    153813    4 drwxr-xr-x   2 root     root         4096 Apr 12  2014 /var/log/dist-upgrade
    153827   40 -rw-rw-r--   1 root     utmp       292292 Dez 23 17:15 /var/log/lastlog
    153814    4 drwxr-xr-x   2 root     root         4096 Jul 23  2014 /var/log/fsck
    131837    4 -rw-r--r--   1 root     root         3750 Jun 23  2016 /var/log/dpkg.log.8.gz
    131784   52 -rw-r--r--   1 root     root        48994 Feb 19 00:37 /var/log/pm-powersave.log
    153815    4 drwxr-xr-x   3 root     root         4096 Jul 23  2014 /var/log/hp
    153832    4 drwxrwxr-x   2 root     lp           4096 Mai 13  2014 /var/log/hp/tmp
    153816    4 drwxr-xr-x   2 root     root         4096 Feb 18 15:20 /var/log/lightdm
    131751    4 -rw-r--r--   1 root     root         1535 Jan 19 23:27 /var/log/pm-powersave.log.2.gz
    131943    4 -rw-r--r--   1 root     root         2340 Jan 20 00:32 /var/log/battery-stats.4
    132385    4 -rw-r--r--   1 root     root          347 Apr 28  2016 /var/log/alternatives.log.10.gz
    131377    4 -rw-r--r--   1 root     root          164 Feb 18 15:13 /var/log/alternatives.log
    131772   12 -rw-r--r--   1 root     root        11784 Dez 22 21:10 /var/log/dpkg.log.3.gz
    153826    4 -rw-r--r--   1 root     root         3450 Aug 18  2016 /var/log/fontconfig.log
    153818    4 drwxr-xr-x   2 root     root         4096 Jan 18  2015 /var/log/unattended-upgrades
    131171    0 -rw-r--r--   1 root     root            0 Jan 18  2015 /var/log/unattended-upgrades/unattended-upgrades-shutdown.log
    131201   28 -rw-rw-r--   1 root     utmp        23040 Feb 19 00:52 /var/log/wtmp
    131723    4 -rw-r--r--   1 root     root         2478 Jan 19 23:33 /var/log/dpkg.log.2.gz
    131337   12 -rw-r--r--   1 root     root        10920 Mär 11  2016 /var/log/dpkg.log.12.gz
    131728    4 -rw-r--r--   1 root     root          316 Dez 24 03:41 /var/log/alternatives.log.2.gz
    131897    4 -rw-r--r--   1 root     root          780 Feb  2 21:35 /var/log/battery-stats.3
    131725    4 -rw-r--r--   1 root     root          925 Feb 10 00:51 /var/log/dpkg.log

**Comment by PhobosK** [comment]
Yeah sorry if I had put too much weight in the title of the bug... 
And sorry to put the /tmp hardcoded problem (that has nothing to do with security) in this bug...
My mistake :) But anyway:


**_Problem 1: Log file world-readable with umask 022_**

> And what confidential information did you find in that file?

Imagine a user wants to check (with _qdirstat_) a folder that has a structure like this:

```
Companies
     Year2017
          Revenue
               UpTo2mlnEUR
                    CompanyX
                    CompanyY
               2-5mlnEUR
                    CompanyZ
```


And it has sparse files in _Companies/Year2017/Revenue/UpTo2mlnEUR/CompanyX_ and _Companies/Year2017/Revenue/2-5mlnEUR/CompanyZ_

What you will get in the log file (**world readable**) would be something like this:

```
[32707] <Debug>   FileInfo.cpp:88 FileInfo():  Found sparse file: /TEST_FOLDER/Companies/Year2017/Revenue/UpTo2mlnEUR/CompanyX/ProductCars.csv   Byte size: 89.1 kB  Allocated: 80.0 kB (160 blocks)
```

What would you call this info? Sensitive/Confidential or OK to be revealed to any user on the system??? 
I could give you even more relevant everyday examples... but I think you got the idea ;)


> As for the log's permissions: The user's umask is of course applied. So as with all files the user creates, it is his choice how restrictive he wants to handle that.

Well by default the UMASK for most systems (DEBIAN based for sure) is 022... so not that restrictive and MOST users do not know how and where to change that... even they hardly are aware of it :).. So one cannot count on that :)


> Obviously it is perfectly acceptable to have log files world readable

Yes most of those usually do not have sensitive info in them at their DEFAULT level of logging but you should consider these too :P (just a snippet):

```
# find /var/log -perm 640 -ls

504 -rw-r-----   1 syslog   adm        509325 Feb 19 10:52 /var/log/syslog
236 -rw-r-----   1 syslog   adm        241328 Feb 19 10:14 /var/log/kern.log
0 -rw-r-----   1 syslog   adm             0 Sep  4 07:35 /var/log/mail.log
4 -rw-r-----   1 root     adm            31 Jul 19  2016 /var/log/dmesg
12 -rw-r-----   1 mysql    adm          8374 Feb 19 10:09 /var/log/mysql/error.log
4 -rw-r-----   1 root     adm            31 Jul 19  2016 /var/log/fsck/checkroot
 4 -rw-r-----   1 root     adm            31 Jul 19  2016 /var/log/fsck/checkfs
```
etc etc of those log files which may have sensitive info in the logging....

Any way you are the developer... it is your choice :)


**_Problem 2: fixed /tmp location_**
Besides the portability argument, *nix is about users' freedom to configure and change things in their system... As a user I have set some variables (like TEMPDIR etc) to use ~/tmp... So I expect applications to consider this and do whatever they do, in a temp dir at that place.... 
Does _qdirstat_ adhere to this standard with a hardcoded tmpdir? 

And IMHO, maybe the app would benefit from a command line switch controlling debugging, so it is easier for the user to chose level of debugging etc, and so debug is not always on....

Anyway as I've already said - you are the developer... so it is your decision... I just took the liberty to let you know about some possible problems with the app :)

Have a nice day...

**Comment by shundhammer** [comment]
You might be interested to hear that this is now changed as a byproduct of log rotation:

Now logging to `/tmp/qdirstat-$USER/qdirstat.log` with the directory set up with permissions 0700.

See also https://github.com/shundhammer/qdirstat/commit/6e7d217c7847c597a294eee39300f057c92fe811 and https://github.com/shundhammer/qdirstat/commit/ee859cb059ca25eb988b6917aacdc6dc6e9b7675 .

**Comment by PhobosK** [comment]
Nice solution ... Thanks
