### ISSUE TITLE
Refresh a file/folder only

### ISSUE THREAD

**Issue by C0rn3j** [shundhammer/qdirstat#53]
This is very useful when cleaning up a folder and wanting to refresh that file/folder only instead of the whole tree, as this can be very slow on HDDs. 

WinDirStat has this feature and I'd love to see it in QDirStat too!

**Comment by shundhammer** [comment]
Context menu -> "Refresh selected" or "File" menu -> "Refresh selected".

What do you think where WinDirStat got this from? :smiley:  Reading an entire root filesystem took a **long** time back in 2001/2003 - 10-20 min the first time, 3-4 min afterwards when it was in the kernel caches.

But to be honest, I don't bother with that anymore these days; the kernel has become so incredibly good at caching that information, file buffer/cache sizes have grown so immensely, and the hardware is so much faster. Rereading my root filesystem or my /work partition takes only very few seconds now - much faster than me figuring out what exactly to select and then picking the right action from the menu.

But it's there if you want it.

**Comment by C0rn3j** [comment]
I've no idea how I missed that, been staring at the context menu yesterday, probably because I was expecting the refresh icon to be nextto it...

Could you add it there? ^^

Sorry and thanks for the history lesson!

**Comment by shundhammer** [comment]
Good icons are a scarce resource. The one "refresh" icon is used for the general complete refresh (where people expect it to be), as is the common F5 keypress. And two different actions need to have different icons.
