### ISSUE TITLE
Directory listing of huge files triggers an overflow

### ISSUE THREAD

**Issue by C0rn3j** [shundhammer/qdirstat#55]
One of the files is 7.7G which seems to be enough for the overflow to happen
![image](https://cloud.githubusercontent.com/assets/1641362/23163321/418135ea-f832-11e6-9ab3-5e0f2d1c1e9b.png)

**Comment by shundhammer** [comment]
Argh. One place where I used `int` instead of `FileSize` (typedef of `long long`) and the compiler didn't complain. Thanks for spotting this!

**Comment by shundhammer** [comment]
Fixed.
