### ISSUE TITLE
QDirStat doesn't scan nested mounted volumes

### ISSUE THREAD

**Issue by C0rn3j** [shundhammer/qdirstat#64]
Not sure if this is by design or set as a workaround, but am reporting it here.

https://i.imgur.com/6uy5W0q.png

If I select /mountables to scan from, it'll show up the folders, including the mounted volumes, but will show them as empty.

If I however scan /mountables/2tbExternal it works just fine.

**Comment by shundhammer** [comment]
https://github.com/shundhammer/qdirstat/blob/master/README.md#old-features

> Not crossing file system boundaries by default so you can see what eats up all the disk space on your root file system without getting distorted numbers due to all the other file systems that are mounted there. If you absolutely wish, you can use "Continue reading at mount point" from the context menu or from the "File" menu -- or configure QDirStat to always read across file systems.
