### ISSUE TITLE
iDirStat GPL infringement

### ISSUE THREAD

**Issue by hyiltiz** [shundhammer/qdirstat#70]
As you know, Tobias Feigl ported QDirStat to OSX with some changes [1], and released the binary as a `.dmg` package [2] under GNU GPLv2. However, he did not release the source code along with the binary. As the author, you could ask him to distribute the source code as well or face licensing issues. I hope not releasing the code wasn't intentional, and he is willing to do so once he is asked to. I am willing to help deal with licensing issues if we face reluctance, as I cannot stand GPL violations.

[1] http://www.tobiasfeigl.de/2017/05/25/mac-free-mac-os-x-alternatives-of-daisydisk-disk-inventory-x-qdirstat-and-windirstat-sierra-10-12-x/#comment-116396
[2] http://www.tobiasfeigl.de/wp-content/uploads/2017/05/idirstat.dmg

**Comment by hyiltiz** [comment]
I was able to compile from scratch using Qt (version below) in less than a minute from your source 7edddebce0f3098fc9f4b1936276042d866eed70, and iDirStat was identical except icon themes and some default settings (exclude `.snapshot` files) to the compiled app as far as I can see.

**Comment by shundhammer** [comment]
That blog doesn't seem to contain any contact e-mail address (which is already annoying). From his bio at that blog and the image he posted on both places, it looks like this is his home page at the university where he works as a researcher / teaching assistant:

  https://www2.cs.fau.de/staff/feigl/index.html

So his e-mail address there appears  to be tobias.feigl@fau.de .

**Comment by shundhammer** [comment]
From the GPL FAQs at https://www.gnu.org/licenses/gpl-faq.en.html :

**_Does the GPL require that source code of modified versions be posted to the public?_**

>The GPL does not require you to release your modified version, or any part of it. You are free to make modifications and use them privately, without ever releasing them. This applies to organizations (including companies), too; an organization can make a modified version and use it internally without ever releasing it outside the organization._

https://www.gnu.org/licenses/gpl-faq.en.html#DoesTheGPLAllowDownloadFee

**_Does the GPL allow me to charge a fee for downloading the program from my distribution site?_**

_Yes. You can charge any fee you wish for distributing a copy of the program. If you distribute binaries by download, you must provide “equivalent access” to download the source—therefore, the fee to download source may not be greater than the fee to download the binary._

https://www.gnu.org/licenses/gpl-faq.en.html#ModifiedJustBinary

**_Can I release a modified version of a GPL-covered program in binary form only?_**

_No. The whole point of the GPL is that all modified versions must be free software—which means, in particular, that the source code of the modified version is available to the users._

https://www.gnu.org/licenses/gpl-faq.en.html#AnonFTPAndSendSources

**_Can I make binaries available on a network server, but send sources only to people who order them?_**

_If you make object code available on a network server, you have to provide the Corresponding Source on a network server as well. The easiest way to do this would be to publish them on the same server, but if you'd like, you can alternatively provide instructions for getting the source from another server, or even a version control system. No matter what you do, the source should be just as easy to access as the object code, though. This is all specified in section 6(d) of GPLv3.

The sources you provide must correspond exactly to the binaries. In particular, you must make sure they are for the same version of the program—not an older version and not a newer version._

**Comment by shundhammer** [comment]
Sent mail (translation below):

> From: Stefan Hundhammer <Stefan.Hundhammer@gmx.de>
> To: tobias.feigl@fau.de
> Subject: iDirStat-Sourcecode
>
> Sehr geehrter Herr Feigl,
>
> Benutzern ist aufgefallen, daß es bei iDirStat, Ihrem MacOS X-Port von QDirStat, keinen Download-Link zum Sourcecode gibt. Ich bin sicher, das ist nur ein Versehen und keine absichtliche GPL-Verletzung. Ich bitte daher darum, diesen Download-Link zu ergänzen. Das einfachste wäre ein Link zum zugehörigen Fork-Projekt auf GitHub, falls es so etwas gibt.
>
> Eine Kontaktadresse auf der gleichen Seite wäre auch sehr nützlich; ich hatte Glück, diese Adresse mit Google zu finden. 
>
> Siehe auch 
>
>  [https://github.com/shundhammer/qdirstat/issues/70] 
>
> (Antwort auch gerne dort möglich)
>
> Viele Grüße aus Nürnberg
>
> Stefan Hundhammer
> Autor von QDirStat  

---------------------

**_Translation:_**

> Dear Mr. Feigl,
>
> users noticed that there is no download link to the source code for iDirStat, your MacOS X port of QDirStat. I am sure this is just an oversight and no intentional GPL violation. So I ask you to add that link. The simplest solution would be a link to the corresponding fork project on GitHub if there is such a thing.
>
> A contact address on the same page would also be very useful; I was lucky to find this address with Google.
>
> See also
>  [https://github.com/shundhammer/qdirstat/issues/70] 
>
> (answer at that place welcome)
>
> Greetings from Nuremberg
>
> Stefan Hundhammer
> QDirStat author

**Comment by hyiltiz** [comment]
Thank you so much! Meanwhile, your code compiles within minutes and works perfectly in macOS 10.12.6 Mac Book Air 13" with QMake version 3.1 using Qt version 5.10.0, all installed through Homebrew. Let me know if you would like any specific thing to be tested in apple platforms, as I have access to Macbook, Macbook Air, Macbook Pro, iMac and iPhone (all belong to friends).

**Comment by aljex** [comment]
Please don't recommend homebrew as long as they are still requiring /usr/local to be owned by a user. It's spreading bad advice and bad practice.

Use macports.

**Comment by hyiltiz** [comment]
Thanks for the advice. I am using it in a single-user environment anyway.

**Comment by slhck** [comment]
@aljex @hyiltiz Homebrew [does not require you to own `/usr/local`](https://github.com/Homebrew/brew/blob/76cd7c79498daf380d99ed7379394618164b602b/Library/Homebrew/cmd/update-report.rb#L289), nor does it not have to be installed there (the `--prefix` option defaults to `/usr/local`, but you can install anywhere you like). Also, under High Sierra, you cannot even own `/usr/local`.

**Comment by aljex** [comment]
Ok, so, the homebrew developers used broken design for years, which they justified with a laughably invalid argument the whole time, until a few months ago Apple finally forced them to change that one detail against their will.

That does not suddenly make homebrew a good system designed and implemented by quality engineers, nor make suggesting it into sound advice.

**Comment by shundhammer** [comment]
Please stay on topic and do not hijack an open issue for something completely unrelated.

**Comment by shundhammer** [comment]
He wrote that he doesn't have any time for this, and that he doesn't have a GitHub repo that he could easily refer to in the blog.  :-(

I waited for some time, but there was no more reply.

So I am going to remove the reference to that project from the QDirStat README.md (which acts as the project's home page).

For my part, I don't want to spend any more time on issues like this.

If any user wants to insist, go ahead; it is really the users' rights granted by the GPL that are violated here. QDirStat is GPL, thus any project derived from it is also GPL.

**Comment by shundhammer** [comment]
I would like to point out that no special license was granted for that other project or its owner; it was solely built and released to the public under the terms of QDirStat's original license, i.e. the GPL V2.

**Comment by hyiltiz** [comment]
Yes, it just changed the name and did release under GPLv2. And although it alluded that some additional changes were made, my test show that nothing but the icons were changed.

**Comment by alisen** [comment]
It seems he shared the source. http://www.tobiasfeigl.de/2020/01/10/mac-idirstat-qdirstat-kdirstat-windirstat-for-os-x/

**Comment by shundhammer** [comment]
> It seems he shared the source. http://www.tobiasfeigl.de/2020/01/10/mac-idirstat-qdirstat-kdirstat-windirstat-for-os-x/

Thanks for the heads-up!
