### ISSUE TITLE
Allow build to specify install prefix

### ISSUE THREAD

**Issue by adrianjohnson** [shundhammer/qdirstat#72]
I couldn't find any way to set the install prefix when building and had the edit the paths in .pro files. It would be useful to provide a documented way to set the install prefix.

**Comment by eclipseo** [comment]
I use:

```make install INSTALL_ROOT=/usr```

It's not at build time though.

**Comment by shundhammer** [comment]
Fixed.

You can now specify the installation prefix during `qmake`:

    qmake INSTALL_PREFIX=/usr/local

Then continue as usual:

    make
    sudo make install

See also https://github.com/shundhammer/qdirstat#install-to-a-custom-directory and the caveat/limitations mentioned there.
