### ISSUE TITLE
Feature request: open the selected file

### ISSUE THREAD

**Issue by dandv** [shundhammer/qdirstat#75]
Use case: I'm finding that some large files are numerically named videos. I'd like to be able to quickly double click on them, see what they're about, and delete if appropriate. I know you can open a file manager in the directory of a give file, but the focus isn't on that file (at least with Nautils).

PS: great to see QDirStat leaving KDE behind! I've had my own [gripes](https://forum.kde.org/viewtopic.php?f=289&t=135101&p=363293#p363293) with it.

**Comment by shundhammer** [comment]
Starting the associated application for any specific file type (MIME type) is as simple as adding a cleanup action with "xdg-open" as the binary to be started; then your desktop will start the predefined application if possible. Or you could simply just start your favourite video player (vlc or whatever you like to use) directly.

Deleting a file is already there, both as "move to trash" and "delete directly" (but be careful with the latter; there is no undelete; this is why there is "move to trash").
