### ISSUE TITLE
show workdir in window title

### ISSUE THREAD

**Issue by olafhering** [shundhammer/qdirstat#77]
It would be cool if the window title is not just "QDirStat", but "QDirStat /dir".
That way it will be simpler to distinguish the individual running qdirstat instances.

**Comment by shundhammer** [comment]
I just did a simple patch (right now living in the huha-url-in-window-title branch https://github.com/shundhammer/qdirstat/tree/huha-url-in-window-title), but I found that I consider that annoying - too much clutter in the window title for my taste.

And I guess that many users will see it the same way, so this should be configurable. But such a config option would have to go to a "general" tab in the config dialog which right now doesn't exist; I had prepared for it, but it was just very few micellaneous seldom used options that would look very lost and unorganized. So I'll postpone this for now.

Until this happens, you could use that branch.

**Comment by olafhering** [comment]
works for me. Perhaps it should only be added if a directory is passed as cmdline option.

**Comment by shundhammer** [comment]
It's now configurable and merged to master:

Enable it in `~/.config/QDirStat/QDirStat.conf`:

    [MainWindow]
    ...
    UrlInWindowTitle=true

You might have to start the latest version of QDirStat with that commit once and close it again to make this option show up.

**Comment by shundhammer** [comment]
![qdirstat-url-in-window-title](https://user-images.githubusercontent.com/11538225/39330914-5563debe-49a3-11e8-8e0e-a521c53162e7.png)
