### ISSUE TITLE
build problem

### ISSUE THREAD

**Issue by rahmanshaber** [shundhammer/qdirstat#78]
i got this when it tries to run after build.
system is linux,manjaro,qt 5.10.1.

![g](https://user-images.githubusercontent.com/30831735/40364494-49742d6a-5df4-11e8-96f5-1ee96346b837.png)

is there any dependencies for it?

**Comment by shundhammer** [comment]
Works fine for everybody who bothers to read the docs.

**Comment by shundhammer** [comment]
Did you even read the output in that screenshot you posted? 
Didn't it strike you as odd that Qt Creator wants to start a binary called `doc` in the `doc/` directory?
Did you even try the command line?
