### ISSUE TITLE
CacheWriter errors go unnoticed much too easily

### ISSUE THREAD

**Issue by Code7R** [shundhammer/qdirstat#86]
Failure to write cache is not reported

Just what the title says. If the target directory is not writable then gzopen returns NULL and this information is only going to the log. The user never gets informed about the problem.

Not sure how you would like to make it reported, the stack trace is pretty clear but using plain QMessageBox looks alien in the rest of the application.

bool CacheWriter::writeCache( const QString & fileName, DirTree *tree )
{
    if ( ! tree || ! tree->root() )
	return false;

    gzFile cache = gzopen( (const char *) fileName.toUtf8(), "w" );

    if ( cache == 0 )
    {
	logError() << "Can't open " << fileName << ": " << formatErrno() << endl;
	return false;
    }

**Comment by shundhammer** [comment]
I'll have a look at that.

**Comment by shundhammer** [comment]
Now posting an error popup.
