### ISSUE TITLE
Show pacman like with WinDirStat instead of "x read jobs"?

### ISSUE THREAD

**Issue by Smile4ever** [shundhammer/qdirstat#87]
I don't know whether you would like to include the famous Pacman icon graphic from WinDirStat into QDirStat. I would love it.

**Comment by shundhammer** [comment]
That "famous PacMan icon" comes from my old KDirStat back in the KDE 2 / 3 days... :smiley:   Like the whole concept of the program, the WinDirStat author copied it.

But...

https://github.com/shundhammer/qdirstat#features-that-are-gone

> KPacman: That was that PacMan animation wile reading directory reading. This is gone now. KPacMan looked out of place pretty soon after it got to KDirStat due to Qt styles doing fancy rendering of widget backgrounds with gradients etc. I know that it does have its fans, but it's unrealistic to get this back without breaking the menu bar rendering.

**Comment by shundhammer** [comment]
See also

https://github.com/shundhammer/kdirstat/blob/master/kdirstat/kpacman.h
https://github.com/shundhammer/kdirstat/blob/master/kdirstat/kpacman.cpp
