### ISSUE TITLE
CLI option for storing of cache file

### ISSUE THREAD

**Issue by jursed** [shundhammer/qdirstat#93]
Hi,

would you find use in adding an "output cache file" flag to the CLI interface?

Use case: periodic monitoring of a storage server, i.e. a non-GUI cron job, which would just store the QDirStat cache file of the scanned directory.

I was looking through the closed Github issues and the readme for similar ideas, but did not find anything. The QDirStat I use currently (presumably [NHellFire's old fork](https://github.com/NHellFire/qdirstat); I'll try building your current release later) only has the `-s` and `-c` options, so perhaps something like `--output-cache | -o` could do the trick.

(FTR, it's definitely just a "nice to have" feature suggestion, nothing critical.)

**Comment by shundhammer** [comment]
It exists, and it's even extensively documented:

https://github.com/shundhammer/qdirstat/blob/master/doc/QDirStat-for-Servers.md
https://github.com/shundhammer/qdirstat/blob/master/doc/cache-file-format.txt

https://github.com/shundhammer/qdirstat#old-features

> Reading and writing cache files:
>
> This is mostly meant for remote servers in some server room somewhere: Rather than installing the Qt and X11 runtime environment and running QDirStat over remote X (ssh with X forwarding), you can run the supplied qdirstat-cache-writer Perl script on the server, copy the resulting cache file to your desktop machine and view the content there with QDirStat.
>
> For large directories (archives etc.) that don't change that much, you can also generate a QDirStat cache file (either with the Perl script or with QDirStat itself) and save it to that corresponding directory. If QDirStat finds a file .qdirstat.cache.gz in a directory, it checks if the toplevel directory in that cache file is the same as the current directory, and if it is, it uses the cache file for that directory rather than reading all subdirectories from disk. If you or the users of that machine use QDirStat often, this might take a lot of I/O load from the server.
>
> If you use the '-l' option of the qdirstat-cache-writer script, it uses the long file format with a complete path for each entry, so you can use the zgrep command with it as a replacement for the locate command.
>
> The KDirStat / QDirStat file format is well documented and very simple. It seems to be used by a number of admins and some backup software. See also the specification in the doc/ directory: https://github.com/shundhammer/qdirstat/blob/master/doc/cache-file-format.txt
>
> You can specify a cache file to read directly at the command line:
>
> qdirstat --cache cache-file

**Comment by jursed** [comment]
[Facepalm]

Thanks...
