### ISSUE TITLE
Release platform binaries?

### ISSUE THREAD

**Issue by hyiltiz** [shundhammer/qdirstat#96]
Since the runtime dependencies can be made much smaller than build dependencies, and `qdirstat` is simply the best in the class, it would be great to make it available to general audience who can simply "click to download and run" without knowing anything about qt (or building software for that matter).

We do not need to be rigorous for this. We can probably start by adopting a travis build script from a similar cross-platform project, and build it. I can offer native testing for macOS, Debian and Windows 10 in x86-64 architectures.

**Comment by shundhammer** [comment]
Well, thank you, but for common distros like Debian, Ubuntu, SUSE, Fedora there are already repositories for binaries for the release versions; see also https://github.com/shundhammer/qdirstat#ready-made-packages .

For SUSE I even offer the latest Git version in a separate repository (with the usual caveat, of course, that this is fresh from development, so there might be more bugs).

Travis is good for things like test builds (including unit tests) in GitHub pull requests, but I have serious doubts how well it works for building end-user binary packages.

Also, never underestimate the ongoing work for ever-changing package dependencies; packages are renamed, split, unified and whatnot in distros, and you have to keep track of that all the time to avoid nasty surprises.

There are platforms out there to take care of building binary packages (e.g. the openSUSE Build Service) or Launchpad. There is a reason that a package has its own maintainer on every one of them -- somebody who knows his way around that platform, and somebody with expert knowledge about the specific distros that the package is built for.

I think the Linux side is already well covered. What QDirStat could use, though, is somebody to take care of MacOS X; so far, MacOS X is still highly experimental, and I guess there are quite a lot of things (cleanups? trash directory handling?) that need better integration into MacOS X.

**Comment by hyiltiz** [comment]
I have been using it in MacOS X for about two years so far, as well as a few friends of mine who received my builds; they simply drag the compiled `.app` binary into their `/Applications/` folder to install and done. It has been running without issues: can handle mounted drives, different file systems, symbolic links, the statistics page also works, saving and loading the cache also works. I am well aware that package building (esp. for every platform) is a huge hassle. But building and maintaining binaries for MacOS (probably not iOS as the file system is not exposed to apps) seems to be straightforward and working across a few devices and OSX versions. 

GNU/Linux users can install via their package managers. macOS users could download from here; at some point, maybe even from Homebrew as bottles.

**Comment by dandv** [comment]
Noob question: I see the older 1.6 version for `focal` at https://packages.ubuntu.com/search?keywords=qdirstat&searchon=names. Is 1.7 available, or does it only work on `groovy`?

**Comment by shundhammer** [comment]
https://repology.org/project/qdirstat/versions

They don't back-port newer versions to already released Ubuntu versions. If there is an up-to-date PPA doing that, I am not aware of it.
