### ISSUE TITLE
Linux Disk Usage Tools Compared: QDirStat vs. K4DirStat vs. Baobab vs. Filelight vs. ncdu

### ISSUE THREAD

**Issue by shundhammer** [shundhammer/qdirstat#97]
### QDirStat

![QDirStat](https://user-images.githubusercontent.com/11538225/55672028-86b72900-5896-11e9-9959-020e692a9567.png)

### K4DirStat

![K4DirStat](https://user-images.githubusercontent.com/11538225/55672029-8a4ab000-5896-11e9-8348-566b971b6931.png)

### Baobab

![Baobab](https://user-images.githubusercontent.com/11538225/55672032-8fa7fa80-5896-11e9-8812-0f882d5ee6a1.png)

### Filelight

![Filelight](https://user-images.githubusercontent.com/11538225/55672034-95054500-5896-11e9-9c37-7a6273660764.png)

### ncdu

![ncdu](https://user-images.githubusercontent.com/11538225/55672037-97679f00-5896-11e9-94ce-9a4118ee66f3.png)

## Performance

All the programs had to scan my /work directory on my (normal rotational, non-SSD) disk, both with cleared kernel directory caches and with caches filled from previous program runs.

To clear those caches on Linux, start a root shell and then enter

```
echo 3 >/proc/sys/vm/drop_caches
```

In all cases, the test procedure was:

- start the program once (without timing) to make sure all shared libraries are loaded and auxiliary processes are started (this might be important for the more complex desktop environments like KDE and GNOME)

- drop caches

- start the program, this time recording the time until the directory tree is fully loaded and the program is ready for user input
- exit the program
- leave caches as they are (i.e. the directory tree is cached by the kernel now)
- start with timing and exit
- start with timing and exit
- start with timing and exit
- drop caches
- start with timing and exit
- drop caches
- start with timing and exit

QDirStat and KDirStat both display the elapsed time for directory reading once that is complete. For the others, a stopwatch was used (which makes the timing somewhat less accurate, of course).

### Benchmark Results: /work

/work is an ext4 filesystem with 230 GB / 216k items on a Samsung 1 TB 7200 rpm disk.

_Update 2019-04-13: Added results from latest QDirStat with performance improvement_

|                   |  Version  | Run 1 | Run 2 | Run 3 | Run 4 | Run 5 | Run 6 |
|----------------|-------------|--------:|-------:|-------:|------:| -------:|---------:|
| _Cache_    |               |  cold   |  hot  |  hot  |  hot  |  cold  |  cold  |
| qdirstat      | 07235ec |   25.8 |   1.5 |  1.5  |  1.6  |  25.3  |  25.2  |
| qdirstat -s  | 07235ec |   24.9 |   1.5 |  1.5  |  1.5  |  24.7  |  24.8  |
| qdirstat      |  1.5        |    32.3 |   1.9 |  2.0  |  2.0  |  33.0  |  33.0  |
| qdirstat -s  |  1.5        |    31.4 |   1.5 |  1.8  |  1.8  |  32.0  |  31.7  |
|                   |               |            |         |         |         |           |       .   |
| k4dirstat    |  3.1.3      |   35.2 |   2.4 |   2.3 |   2.4 |   34.3  |  34.2  |
| baobab      |  3.28.0   |   24.6 |   3.5 |    3.5 |   3.4 |   24.7  |  24.1  |
| filelight       | 4.17       |   19.8 |   1.1 |    1.2 |   1.1 |   19.2  |  19.5  |
| ncdu          |  1.12      |   18.6 |   1.5 |    1.2 |   1.3 |   19.0  |  19.0  |
| du -hs        |  8.28      |   17.9 |   0.5 |    0.5 |  0.5  |   18.0  |  18.0  |

The exact command for `du -hs` was `time du -hs /work`, so the timing was more accurate than with a stopwatch.

Don't get all hung up with split seconds at the results for baobab, filelight and ncdu: Operating a manual stopwatch isn't all that accurate with one hand on the keyboard and the other at the stopwatch.

## Benchmark Conclusions

`du -hs` doesn't do much; it doesn't have a user interface. So this can safely be considered the theoretical minimum how fast this can possibly get: Traverse an entire directory tree, open each directory in sequence (using the `opendir()` / `readdir()` / `closedir()` syscalls) and obtain detailed information from the filesystem for each file or directory encountered (using the `stat()` or `lstat()` syscalls).

ncdu comes close. Since it uses a text-based (ncurses) user interface, it doesn't have much overhead for GUI stuff. On the other hand, it also can't do very much (but it can delete the selected file).

Filelight is really fast. In particular, re-reading the same directory appears to be faster than with ncdu (but this might be attributed to the inaccuracies of using a manual stopwatch). According to the output of `ps`, it uses 3 threads (thus 3 CPU cores); however since this is largely I/O bound, it is not obvious how this helps.

Baobab is fast for uncached reads, but surprisingly slow for the cached ones. But it doesn't keep any information about individual files in memory, only the directories with the sums. That's why it only offers to delete entire subdirectories, but not individual files (duh!).

K4DirStat is a little slower than QDirStat 1.5, even though both use the same directory reading code (inherited from KDirStat). This might be because of more display updates and because of re-sorting the diplayed tree all the time during reading. It is significantly slower than the latest QDirStat with the performance improvements, though.

QDirStat becomes a little faster with the `-s` (`--slow-updates`) command line option which was designed for remote X connections that have become very slow with Qt5 (due to always using a pixel buffer that has to be transferred over the network connnection instead of X protocol draw primitives like `XDrawString()`). But the difference is really negligible.

The latest QDirStat from Git master got quite some performance improvements due to using `fstatat()` instead of `lstat()` and sorting the directory entries by i-no before that call so the corresponding i-nodes can be read sequentially with minimized disk seek times (which has no effect on SSDs, though).

## Features

| Feature                                         | QDirStat | K4DirStat | Baobab | Filelight | ncdu | du |
|---------------------------------------------|:-----------:|:-------------:|:-----------:|:----------:|:-------:|:----|
| Show tree total size                     | +            | +               | +            | +          | +        | +   |
| Show subtree size                       | +            | +               | +            | +          | +        | +   |
| Show size of individual files        | +            | +               |                | +          | +        | +   |
| Stop at mounted filesystems       | +            | +               | +            | +           |           | +   |
| Exclude rules                               | +            | +               |               | +           |           | +   |
| Show treemap                             | +            | +               |               |              |           |      |
| Show some other graph              |               |                  | +            | +           |           |      |
| Delete a file                                 | +            | +               |               | +           | +        |      |
| Delete a directory / subtree         | +            | +               | +            | +           | +        |      |
| Open directory in filemanager     | +            | +               | +            | +           |           |      |
| Custom cleanup actions              | +            | +               |               |              |           |      |
| File type view                              | +            |                   |               |              |           |      |
| File size histogram view              | +            |                   |               |              |           |      |
| Package manager support          | +            |                   |               |              |           |      |
| Proper Btrfs subvol handling       | +            | ?                | ?            | ?           | ?        | ?   |

### Size Units

Baobab shows all sizes in 1000-based units, not 1024-based like all the others. That's why the sizes appear to be different (but they really are not).

| Unit   |         1000-based |        1024-based |
|--------:|-----------------------:|-----------------------:|
| 1 KB  |                1000 B |                1024 B |
| 1 MB |        1,000,000 B |        1,048,576 B |
| 1 GB | 1,000,000,000 B | 1,073,741,824 B |

## Versions Used

All running on Xubuntu 18.04.02 LTS with all the latest updates.

| Program         | Version                                                |
|-------------------|----------------------------------------------------|
| QDirStat        | Git master (07235ec6b658, post-1.5)  |
| QDirStat        | 1.5                                                        |
| K4DirStat      | 3.1.3-1                                                  |
| Baobab         | 3.28.0-1                                                |
| Filelight         | 4:17.12.3-0                                           |
| ncdu              | 1.12-1                                                  |
| du                 | coreutils-8.28                                       |

## Hardware

- Intel Core i7 870 2.93 GHz
- 16 GB RAM
- 2 * HD Samsung SpinPoint F3 (HD103SJ) 1 TB, 7200 rpm
- Samsung SSD 860 250 GB (not used in this test)

**Comment by shundhammer** [comment]
Feel free to comment to this issue. That is the main reason why I used this issue tracker instead of the GitHub wiki (the other being that the wiki does not support this nice uploading of screenshots that the issue tracker has).

**Comment by martin-eden** [comment]
Hello Stefan,

> Feel free to comment to this issue. That is the main reason why I used this issue tracker instead of the GitHub wiki

Features table is obviously biased and looks like advertisement

I'm doing my own code projects and trying to __feel__ what some offered tool __is__.

It's quite hard to represent tools in one bitmap. But let's instead of list of "cool features" use list of "essential traits". (And this "essential" list is always personal.)

| Name       | Linux | Widely available | Machine-readable output | Dedication       |
|:----------:|:-----:|:----------------:|:-----------------------:|:----------------:|
| QDirstat   |  ☑    | ☐                | ☐                       | space management |
| Filelight  |  ☑    | ☐                | ☐                       | visualization    |
| WinDirStat |  ☐    | ☑                | ☐                       | visualization    |
| du         |  ☑    | ☑                | ☑                       | data processing  |

Right tool for me is not with most checks in boxes. Right tool has what I need and nothing more.

Personally, I'm using QDirStat because

* I love visualizations (check out my [BinToImg](https://github.com/martin-eden/Lua-BinToImg)!)
* I'm using Linux
* I appreciate histograms and file statistics (keys F2, F3)
* I appreciate exclusion rules (to exclude huge `.git/`)
* I like your dedication to this project, your discipline and probably your code style

**Comment by shundhammer** [comment]
Sure there is machine-readable output:

https://github.com/shundhammer/qdirstat/blob/master/doc/cache-file-format.txt

Generate with "File" -> "Write to Cache File" or with the [qdirstat-cache-writer](
https://github.com/shundhammer/qdirstat/blob/master/scripts/README.md) script. This has been available since about 2002 or 2003. 😃

**Comment by martin-eden** [comment]
Didn't know about that.


|            | Machine-readable output |
|:----------:|:-----------------------:|
| QDirstat   | ☑                       |

**Comment by shundhammer** [comment]
> Didn't know about that.

It's right there in the menus, and there are several documents about it in the `doc/` subdirectory, showing it from several aspects and in several use cases, including server machines sitting in a rack in some data center without any graphical console, just `ssh` access. This is why this:

> Features table is obviously biased and looks like advertisement

Is a very uninformed and naive statement. My table doesn't even list all the major features, let alone those that were implemented after 2019 when I did those benchmarks.

It turns out you never even discovered many of the features. There is documentation about every single of them; like

- Finding the package that a system file belongs to
- The packages view
- The unpackaged files view
- The file age view
- The "Discover" actions
- Finding files by name
- Handling allocated size vs. nominal byte size
- Handling hard links to prevent counting the same file multiple times

I am not even talking about the file size distribution view, or the file type view (which has very limited use, a one-digit number of users wanted it because WinDirStat has it).

>I'm doing my own code projects and trying to feel what some offered tool is.

Being really informed by reading the documentation beats _feeling_ something every time. Only then you know what's really available, and what each feature is useful for. Of course not every featue is useful for everybody; that's the nature of things. But just discounting it because you don't have that use case is shortsighted.

No, it's in no way, shape or form just about advertising. If anything, the table is too short, so the limited tools look far better than they should; but then, many features were introduced after I made this benchmark and the table.

**Comment by martin-eden** [comment]
Reading documentation is the next resort after trying to figure it out and googling. (Next is reading source and reading binary.)

We're going off-topic here and it's becoming personal. Still I provide my opinion. Please take it with grain of salt.

Documentation is "mommy told you" contract. Why not change cursor key actions to "Space + Shift" for "←", "Space + D" for "→", "Space + W" for "↑", "Space + A" for "↓"? Try it, it's convenient. And then document them properly and require all users to read documentation. (And also document there a lot more tangentially related things. User must feel that he did a good job by reading that doc. He also must feel how miserable is his demands comparing to great possibilities that tool provides.)

This project has no bounded scope. You're just adding integrations for your common tasks. Which are sometimes useful for other users (including me). So it's more like file manager with treemap than treemap tool over files. (That's how _I feel_ no matter what _documentation says_.)

I'm aware of histograms and file statistics. And wrote it in initial post. They are unique features and not eligible for comparison.

Your comparison table is biased because you're author of one of participant tools. For me as a passing-by user value of this page is in tool names and screenshots.

There _must_ be advertisement page. There _may_ be separate comparison page.
