### ISSUE TITLE
Suggestion: Remove dependency to URI in qdirstat-cache-writer

### ISSUE THREAD

**Issue by phiresky** [shundhammer/qdirstat#98]
Pretty much every time I want to use qdirstat on a server by running

```bash
wget https://raw.githubusercontent.com/shundhammer/qdirstat/master/scripts/qdirstat-cache-writer
perl qdirstat-cache-writer /
```

I get

`Can't locate URI/Escape.pm in @INC (you may need to install the URI::Escape module)`

Then I need to search, each time, what the uri package is called and run `apt install liburi-perl`, or if I don't have root work around in some other way. 

Since it seems like the only thing needed is the uri_escape function and everything else works without dependencies in a base perl installation, it would be great if you could remove that dependency (e.g. [just copy it](https://github.com/libwww-perl/URI/blob/master/lib/URI/Escape.pm) since it is also licensed under GPL).

**Comment by shundhammer** [comment]
This is contrary to the "don't roll your own" mantra that everybody else keeps preaching all the time.

Copying a piece of library code means not getting any updates, i.e. no bug fixes, no security fixes.

**Comment by shundhammer** [comment]
If you decide you want to take over that responsibility for yourself and your machines, I suggest you copy & paste that code into your personal version and put it on one of your machines where you can easily `wget` it from; or even in a GitHub fork repository of QDirStat where you keep those changes in a private branch.

The qdirstat-cache-writer doesn't change all that often; it should be fairly easy to check every once in a while what has changed there and rebase that private branch accordingly.

You don't need to also build QDirStat itself from that GitHub fork; only the qdirstat-cache-writer would be sufficient.

**Comment by phiresky** [comment]
> This is contrary to the "don't roll your own" mantra

Of course it's a tradeoff.. But it's a single function that doesn't really do much, especially in the way you use it. I don't know any perl but to me it looks like your use would be pretty much replaceable by

```
for (0..255) {
    $escapes{chr($_)} = sprintf("%%%02X", $_);
}

 $text =~ s/[\x00-\x20%]/$escapes{$1}/ge;
```

Or maybe just using some other random escaping function, seems like you really only need to escape [\t\n ].

If you still don't like that, feel free to reinterpret my issue as 

"Suggestion: provide a one line command to run qdirstat on a server that should look similar to

`ssh user@server 'curl https://github.com/.. -o /tmp/qw && perl /tmp/qw -o -' | qdirstat -c -`


I'm pretty sure this would also be useful to others to put in the README - for anyone trying to run it on a server instead of just mentioning that perl script exists and letting them figure it out.
